// Generated from Resources/UiStrings.resx. Do not edit.
export const TextKeys = {
  Appearance: {
    Dark: "Appearance.Dark",
    Language: "Appearance.Language",
    Light: "Appearance.Light",
    System: "Appearance.System",
    Theme: "Appearance.Theme",
  },
  Census: {
    Attribution: "Census.Attribution",
    CustomCount: "Census.CustomCount",
    DrawingHint: "Census.DrawingHint",
    Estimate: "Census.Estimate",
    GridResidents: "Census.GridResidents",
    LoadFailed: "Census.LoadFailed",
    Loading: "Census.Loading",
    Population: "Census.Population",
    Source: "Census.Source",
    SourcePopulation: "Census.SourcePopulation",
    Unavailable: "Census.Unavailable",
    Wait: "Census.Wait",
  },
  Common: {
    ApiError: "Common.ApiError",
    Cancel: "Common.Cancel",
    Close: "Common.Close",
    Collapse: "Common.Collapse",
    CommunicationError: "Common.CommunicationError",
    Copied: "Common.Copied",
    Copy: "Common.Copy",
    DismissError: "Common.DismissError",
    Error: "Common.Error",
    ErrorDetails: "Common.ErrorDetails",
    Expand: "Common.Expand",
    HoursAgo: "Common.HoursAgo",
    JustNow: "Common.JustNow",
    Loading: "Common.Loading",
    Maximize: "Common.Maximize",
    Minimize: "Common.Minimize",
    MinutesAgo: "Common.MinutesAgo",
    Open: "Common.Open",
    Optional: "Common.Optional",
    Refresh: "Common.Refresh",
    Reload: "Common.Reload",
    Remove: "Common.Remove",
    Restore: "Common.Restore",
    Retry: "Common.Retry",
    Save: "Common.Save",
    UnhandledError: "Common.UnhandledError",
    View: "Common.View",
    ViewFailed: "Common.ViewFailed",
  },
  Demo: {
    BackupShelter: "Demo.BackupShelter",
    Coordinates: "Demo.Coordinates",
    Description: "Demo.Description",
    EastExit: "Demo.EastExit",
    Exit: "Demo.Exit",
    MainExit: "Demo.MainExit",
    MainShelter: "Demo.MainShelter",
    NorthAssembly: "Demo.NorthAssembly",
    NorthShelter: "Demo.NorthShelter",
    SampleData: "Demo.SampleData",
    SouthAssembly: "Demo.SouthAssembly",
    SouthShelter: "Demo.SouthShelter",
    Title: "Demo.Title",
  },
  Direction: {
    East: "Direction.East",
    North: "Direction.North",
    NorthEast: "Direction.NorthEast",
    NorthWest: "Direction.NorthWest",
    South: "Direction.South",
    SouthEast: "Direction.SouthEast",
    SouthWest: "Direction.SouthWest",
    West: "Direction.West",
  },
  Drawing: {
    BlockadeEnd: "Drawing.BlockadeEnd",
    BlockadeStart: "Drawing.BlockadeStart",
    Cancel: "Drawing.Cancel",
    Category: "Drawing.Category",
    Circle: "Drawing.Circle",
    Done: "Drawing.Done",
    EvacuationCenter: "Drawing.EvacuationCenter",
    EvacuationPolygon: "Drawing.EvacuationPolygon",
    EvacuationZone: "Drawing.EvacuationZone",
    FirstPoint: "Drawing.FirstPoint",
    Instructions: "Drawing.Instructions",
    Navigate: "Drawing.Navigate",
    Polygon: "Drawing.Polygon",
    PolygonAdded: "Drawing.PolygonAdded",
    PolygonMinimum: "Drawing.PolygonMinimum",
    PolygonVertices: "Drawing.PolygonVertices",
    RadiusHint: "Drawing.RadiusHint",
    SafeCenter: "Drawing.SafeCenter",
    SafePolygon: "Drawing.SafePolygon",
    SecondPoint: "Drawing.SecondPoint",
    Shape: "Drawing.Shape",
    ShapeHint: "Drawing.ShapeHint",
    StartHint: "Drawing.StartHint",
    Tools: "Drawing.Tools",
  },
  Evacuation: {
    ActiveSession: "Evacuation.ActiveSession",
    Analyzing: "Evacuation.Analyzing",
    AssignedShelter: "Evacuation.AssignedShelter",
    Assigning: "Evacuation.Assigning",
    Description: "Evacuation.Description",
    Direction: "Evacuation.Direction",
    GoogleMaps: "Evacuation.GoogleMaps",
    Heading: "Evacuation.Heading",
    Introduction: "Evacuation.Introduction",
    Loading: "Evacuation.Loading",
    LoadingDetails: "Evacuation.LoadingDetails",
    NoAssignment: "Evacuation.NoAssignment",
    OutsideDescription: "Evacuation.OutsideDescription",
    OutsideTitle: "Evacuation.OutsideTitle",
    PageTitle: "Evacuation.PageTitle",
    Plan: "Evacuation.Plan",
    Refresh: "Evacuation.Refresh",
    RouteInstructions: "Evacuation.RouteInstructions",
    Routing: "Evacuation.Routing",
    Session: "Evacuation.Session",
    SessionExpired: "Evacuation.SessionExpired",
    SessionId: "Evacuation.SessionId",
    SessionLabel: "Evacuation.SessionLabel",
    Start: "Evacuation.Start",
    Title: "Evacuation.Title",
    WalkingTime: "Evacuation.WalkingTime",
    ZoneRequired: "Evacuation.ZoneRequired",
  },
  EvacuationUi: {
    Appearance: "EvacuationUi.Appearance",
    Assignment: "EvacuationUi.Assignment",
    BearingHint: "EvacuationUi.BearingHint",
    CancelCorrection: "EvacuationUi.CancelCorrection",
    Checking: "EvacuationUi.Checking",
    CorrectMap: "EvacuationUi.CorrectMap",
    CorrectionHint: "EvacuationUi.CorrectionHint",
    Details: "EvacuationUi.Details",
    Direction: "EvacuationUi.Direction",
    Dismiss: "EvacuationUi.Dismiss",
    Expired: "EvacuationUi.Expired",
    FindingLocation: "EvacuationUi.FindingLocation",
    FindingShelter: "EvacuationUi.FindingShelter",
    Fit: "EvacuationUi.Fit",
    FitHint: "EvacuationUi.FitHint",
    FullShelter: "EvacuationUi.FullShelter",
    GpsDenied: "EvacuationUi.GpsDenied",
    GpsError: "EvacuationUi.GpsError",
    GpsInsecure: "EvacuationUi.GpsInsecure",
    GpsTimeout: "EvacuationUi.GpsTimeout",
    GpsUnavailable: "EvacuationUi.GpsUnavailable",
    GpsUnsupported: "EvacuationUi.GpsUnsupported",
    HideMap: "EvacuationUi.HideMap",
    Information: "EvacuationUi.Information",
    Legend: "EvacuationUi.Legend",
    LoadError: "EvacuationUi.LoadError",
    Loading: "EvacuationUi.Loading",
    LoadingLabel: "EvacuationUi.LoadingLabel",
    LocationHelp: "EvacuationUi.LocationHelp",
    LocationHint: "EvacuationUi.LocationHint",
    MapLabel: "EvacuationUi.MapLabel",
    MapSelectLabel: "EvacuationUi.MapSelectLabel",
    MapTools: "EvacuationUi.MapTools",
    Navigate: "EvacuationUi.Navigate",
    NewTab: "EvacuationUi.NewTab",
    NoAssignment: "EvacuationUi.NoAssignment",
    NoShelter: "EvacuationUi.NoShelter",
    NotSet: "EvacuationUi.NotSet",
    Outside: "EvacuationUi.Outside",
    PageTitle: "EvacuationUi.PageTitle",
    PickHint: "EvacuationUi.PickHint",
    Places: "EvacuationUi.Places",
    PlanUnavailable: "EvacuationUi.PlanUnavailable",
    PreviewHint: "EvacuationUi.PreviewHint",
    RefreshGps: "EvacuationUi.RefreshGps",
    RefreshPage: "EvacuationUi.RefreshPage",
    RetryGps: "EvacuationUi.RetryGps",
    SelectMap: "EvacuationUi.SelectMap",
    SelectMyLocation: "EvacuationUi.SelectMyLocation",
    SelectedCoordinates: "EvacuationUi.SelectedCoordinates",
    ShowMap: "EvacuationUi.ShowMap",
    UseGps: "EvacuationUi.UseGps",
    WalkingTime: "EvacuationUi.WalkingTime",
    Where: "EvacuationUi.Where",
    WrongPlan: "EvacuationUi.WrongPlan",
    YourShelter: "EvacuationUi.YourShelter",
  },
  EvacuationUx: {
    ChangeLocation: "EvacuationUx.ChangeLocation",
    CollapsePanel: "EvacuationUx.CollapsePanel",
    ConfirmLocation: "EvacuationUx.ConfirmLocation",
    ExpandPanel: "EvacuationUx.ExpandPanel",
    GpsConfirmed: "EvacuationUx.GpsConfirmed",
    GpsDenied: "EvacuationUx.GpsDenied",
    GpsError: "EvacuationUx.GpsError",
    GpsInsecure: "EvacuationUx.GpsInsecure",
    GpsPending: "EvacuationUx.GpsPending",
    GpsTimeout: "EvacuationUx.GpsTimeout",
    GpsUnavailable: "EvacuationUx.GpsUnavailable",
    GpsUnsupported: "EvacuationUx.GpsUnsupported",
    LocationHint: "EvacuationUx.LocationHint",
    MapConfirmed: "EvacuationUx.MapConfirmed",
    OutsideHint: "EvacuationUx.OutsideHint",
    PickInside: "EvacuationUx.PickInside",
    PickOnMap: "EvacuationUx.PickOnMap",
    ShelterDetails: "EvacuationUx.ShelterDetails",
  },
  Location: {
    Acquired: "Location.Acquired",
    Active: "Location.Active",
    BrowserMessage: "Location.BrowserMessage",
    Coordinates: "Location.Coordinates",
    Correct: "Location.Correct",
    DefaultPosition: "Location.DefaultPosition",
    Denied: "Location.Denied",
    DismissWarning: "Location.DismissWarning",
    Error: "Location.Error",
    ErrorTitle: "Location.ErrorTitle",
    Get: "Location.Get",
    Getting: "Location.Getting",
    GpsPosition: "Location.GpsPosition",
    HttpsRequired: "Location.HttpsRequired",
    InsecureConnection: "Location.InsecureConnection",
    InsecureHost: "Location.InsecureHost",
    LocalhostHint: "Location.LocalhostHint",
    ManualFallback: "Location.ManualFallback",
    Mark: "Location.Mark",
    MarkTitle: "Location.MarkTitle",
    NavigationHint: "Location.NavigationHint",
    NetworkAcquired: "Location.NetworkAcquired",
    NotSet: "Location.NotSet",
    OrMark: "Location.OrMark",
    PermissionHint: "Location.PermissionHint",
    ProvisionalCoordinates: "Location.ProvisionalCoordinates",
    ProvisionalHint: "Location.ProvisionalHint",
    Refresh: "Location.Refresh",
    SecureHint: "Location.SecureHint",
    SelectHint: "Location.SelectHint",
    SelectInZone: "Location.SelectInZone",
    SelectedCoordinates: "Location.SelectedCoordinates",
    SelectionMode: "Location.SelectionMode",
    Set: "Location.Set",
    Timeout: "Location.Timeout",
    Unavailable: "Location.Unavailable",
    Unsupported: "Location.Unsupported",
    Verify: "Location.Verify",
    YourPosition: "Location.YourPosition",
  },
  Map: {
    AssemblyPoint: "Map.AssemblyPoint",
    Blockade: "Map.Blockade",
    BlockadeName: "Map.BlockadeName",
    BlockadePosition: "Map.BlockadePosition",
    Blockades: "Map.Blockades",
    Center: "Map.Center",
    CollapseInfo: "Map.CollapseInfo",
    Contributors: "Map.Contributors",
    EvacuationZone: "Map.EvacuationZone",
    EvacuationZoneName: "Map.EvacuationZoneName",
    EvacuationZones: "Map.EvacuationZones",
    ExpandInfo: "Map.ExpandInfo",
    FeatureSummary: "Map.FeatureSummary",
    Features: "Map.Features",
    FitShelters: "Map.FitShelters",
    GestureHint: "Map.GestureHint",
    HideZone: "Map.HideZone",
    Length: "Map.Length",
    NoZone: "Map.NoZone",
    Radius: "Map.Radius",
    ResetView: "Map.ResetView",
    SafeLocation: "Map.SafeLocation",
    SafeLocations: "Map.SafeLocations",
    SafePoint: "Map.SafePoint",
    SafeZone: "Map.SafeZone",
    SafeZoneName: "Map.SafeZoneName",
    Vertices: "Map.Vertices",
    ZoneInfo: "Map.ZoneInfo",
    ZoomIn: "Map.ZoomIn",
    ZoomOut: "Map.ZoomOut",
  },
  Navigation: {
    Demo: "Navigation.Demo",
    DemoTitle: "Navigation.DemoTitle",
    Label: "Navigation.Label",
    Map: "Navigation.Map",
    MapTitle: "Navigation.MapTitle",
    Menu: "Navigation.Menu",
    NotFound: "Navigation.NotFound",
    NotFoundDescription: "Navigation.NotFoundDescription",
    Simulator: "Navigation.Simulator",
  },
  Publish: {
    Address: "Publish.Address",
    AssemblyPoints: "Publish.AssemblyPoints",
    Blockades: "Publish.Blockades",
    ChangeSettings: "Publish.ChangeSettings",
    CitizenView: "Publish.CitizenView",
    CloseProjector: "Publish.CloseProjector",
    CodeLabel: "Publish.CodeLabel",
    CopyFailed: "Publish.CopyFailed",
    CopyLink: "Publish.CopyLink",
    CopySuccess: "Publish.CopySuccess",
    Description: "Publish.Description",
    HttpError: "Publish.HttpError",
    LinkCopied: "Publish.LinkCopied",
    LinkLabel: "Publish.LinkLabel",
    NextPerson: "Publish.NextPerson",
    OpenHint: "Publish.OpenHint",
    Plan: "Publish.Plan",
    Projector: "Publish.Projector",
    ProjectorHint: "Publish.ProjectorHint",
    ProjectorTitle: "Publish.ProjectorTitle",
    Publishing: "Publish.Publishing",
    PublishingPlan: "Publish.PublishingPlan",
    QrLabel: "Publish.QrLabel",
    Ready: "Publish.Ready",
    ReviewHint: "Publish.ReviewHint",
    Scan: "Publish.Scan",
    Scenario: "Publish.Scenario",
    SessionCode: "Publish.SessionCode",
    SettingsDescription: "Publish.SettingsDescription",
    ShareHint: "Publish.ShareHint",
    ShareInstructions: "Publish.ShareInstructions",
    ShareTitle: "Publish.ShareTitle",
    Submit: "Publish.Submit",
    Success: "Publish.Success",
    Summary: "Publish.Summary",
    Title: "Publish.Title",
    Zones: "Publish.Zones",
  },
  Scenario: {
    Actions: "Scenario.Actions",
    Active: "Scenario.Active",
    Branch: "Scenario.Branch",
    BranchCurrent: "Scenario.BranchCurrent",
    BranchFrom: "Scenario.BranchFrom",
    BranchName: "Scenario.BranchName",
    ClearFilter: "Scenario.ClearFilter",
    CopyDescription: "Scenario.CopyDescription",
    CopyFeatures: "Scenario.CopyFeatures",
    CopyTree: "Scenario.CopyTree",
    Count: "Scenario.Count",
    CreateAndSwitch: "Scenario.CreateAndSwitch",
    CreateDescription: "Scenario.CreateDescription",
    CreateTitle: "Scenario.CreateTitle",
    Creating: "Scenario.Creating",
    Current: "Scenario.Current",
    Delete: "Scenario.Delete",
    DeleteConfirm: "Scenario.DeleteConfirm",
    DeleteNamed: "Scenario.DeleteNamed",
    Description: "Scenario.Description",
    DescriptionHint: "Scenario.DescriptionHint",
    FeatureSummary: "Scenario.FeatureSummary",
    Features: "Scenario.Features",
    Filter: "Scenario.Filter",
    FilterHint: "Scenario.FilterHint",
    Label: "Scenario.Label",
    Loading: "Scenario.Loading",
    NameExample: "Scenario.NameExample",
    NamePlaceholder: "Scenario.NamePlaceholder",
    NameRequired: "Scenario.NameRequired",
    NewBranch: "Scenario.NewBranch",
    NoMatches: "Scenario.NoMatches",
    OpenTree: "Scenario.OpenTree",
    Parent: "Scenario.Parent",
    Root: "Scenario.Root",
    Session: "Scenario.Session",
    Switch: "Scenario.Switch",
    SwitchHint: "Scenario.SwitchHint",
    Tree: "Scenario.Tree",
    TreeCopied: "Scenario.TreeCopied",
  },
  Shelter: {
    Allocation: "Shelter.Allocation",
    AllocationTitle: "Shelter.AllocationTitle",
    Criterion: "Shelter.Criterion",
    DecreaseDistance: "Shelter.DecreaseDistance",
    DecreaseOccupancy: "Shelter.DecreaseOccupancy",
    DefaultName: "Shelter.DefaultName",
    Distance: "Shelter.Distance",
    DistanceArrow: "Shelter.DistanceArrow",
    DistanceLabel: "Shelter.DistanceLabel",
    DistanceOnly: "Shelter.DistanceOnly",
    DistancePercent: "Shelter.DistancePercent",
    DistanceValue: "Shelter.DistanceValue",
    DistanceWeight: "Shelter.DistanceWeight",
    Full: "Shelter.Full",
    IncreaseDistance: "Shelter.IncreaseDistance",
    IncreaseOccupancy: "Shelter.IncreaseOccupancy",
    Label: "Shelter.Label",
    Occupancy: "Shelter.Occupancy",
    OccupancyArrow: "Shelter.OccupancyArrow",
    OccupancyLabel: "Shelter.OccupancyLabel",
    OccupancyLabelAccessible: "Shelter.OccupancyLabelAccessible",
    OccupancyOnly: "Shelter.OccupancyOnly",
    OccupancyPercent: "Shelter.OccupancyPercent",
    OccupancySummary: "Shelter.OccupancySummary",
    OccupancyValue: "Shelter.OccupancyValue",
    OccupancyWeight: "Shelter.OccupancyWeight",
    PeopleCount: "Shelter.PeopleCount",
    PeopleHere: "Shelter.PeopleHere",
    Places: "Shelter.Places",
    PresetA: "Shelter.PresetA",
    PresetB: "Shelter.PresetB",
    PresetC: "Shelter.PresetC",
    Presets: "Shelter.Presets",
    ResetOccupancy: "Shelter.ResetOccupancy",
    SelectHint: "Shelter.SelectHint",
    WeightsLabel: "Shelter.WeightsLabel",
    WeightsValue: "Shelter.WeightsValue",
  },
  Simulation: {
    ActualSpeed: "Simulation.ActualSpeed",
    AgentCount: "Simulation.AgentCount",
    AgentCountLabel: "Simulation.AgentCountLabel",
    AgentCountValue: "Simulation.AgentCountValue",
    AgentPerDotUnit: "Simulation.AgentPerDotUnit",
    AgentPositions: "Simulation.AgentPositions",
    AgentSpeed: "Simulation.AgentSpeed",
    AgentSummary: "Simulation.AgentSummary",
    AgentViewHint: "Simulation.AgentViewHint",
    Agents: "Simulation.Agents",
    AgentsPerDot: "Simulation.AgentsPerDot",
    AgentsPerDotLabel: "Simulation.AgentsPerDotLabel",
    AgentsPerDotUnit: "Simulation.AgentsPerDotUnit",
    AgentsPerDotValue: "Simulation.AgentsPerDotValue",
    ChangeSpeed: "Simulation.ChangeSpeed",
    Close: "Simulation.Close",
    CloseHint: "Simulation.CloseHint",
    Completed: "Simulation.Completed",
    Controls: "Simulation.Controls",
    Coordinates: "Simulation.Coordinates",
    Current: "Simulation.Current",
    Defaults: "Simulation.Defaults",
    Density: "Simulation.Density",
    DensityMap: "Simulation.DensityMap",
    DestinationRequired: "Simulation.DestinationRequired",
    Diagnostics: "Simulation.Diagnostics",
    Dimensions: "Simulation.Dimensions",
    DimensionsValue: "Simulation.DimensionsValue",
    DismissMessage: "Simulation.DismissMessage",
    DisplayMode: "Simulation.DisplayMode",
    DisplayRefresh: "Simulation.DisplayRefresh",
    DisplayRefreshOption: "Simulation.DisplayRefreshOption",
    DisplaySettings: "Simulation.DisplaySettings",
    DotCount: "Simulation.DotCount",
    Elapsed: "Simulation.Elapsed",
    Ended: "Simulation.Ended",
    Engine: "Simulation.Engine",
    EngineHint: "Simulation.EngineHint",
    Evacuated: "Simulation.Evacuated",
    EvacuatedProgress: "Simulation.EvacuatedProgress",
    Evacuation: "Simulation.Evacuation",
    FlowParticles: "Simulation.FlowParticles",
    FpsLimit: "Simulation.FpsLimit",
    Live: "Simulation.Live",
    LoadingParameters: "Simulation.LoadingParameters",
    MapDisplay: "Simulation.MapDisplay",
    MaxAgentsPerDot: "Simulation.MaxAgentsPerDot",
    OneAgentPerDot: "Simulation.OneAgentPerDot",
    OpenSettings: "Simulation.OpenSettings",
    Parameters: "Simulation.Parameters",
    Pause: "Simulation.Pause",
    PauseHint: "Simulation.PauseHint",
    Paused: "Simulation.Paused",
    PhysicsDescription: "Simulation.PhysicsDescription",
    PopulationSettings: "Simulation.PopulationSettings",
    Preparing: "Simulation.Preparing",
    RayLength: "Simulation.RayLength",
    RayLengthLabel: "Simulation.RayLengthLabel",
    RealTime: "Simulation.RealTime",
    RenderFps: "Simulation.RenderFps",
    Repulsion: "Simulation.Repulsion",
    RepulsionLabel: "Simulation.RepulsionLabel",
    RepulsionValue: "Simulation.RepulsionValue",
    Reset: "Simulation.Reset",
    ResetAgents: "Simulation.ResetAgents",
    ResetHint: "Simulation.ResetHint",
    ResumeHint: "Simulation.ResumeHint",
    Run: "Simulation.Run",
    Running: "Simulation.Running",
    SensorHint: "Simulation.SensorHint",
    Sensors: "Simulation.Sensors",
    Settings: "Simulation.Settings",
    SettingsDescription: "Simulation.SettingsDescription",
    SettingsTitle: "Simulation.SettingsTitle",
    ShowSensors: "Simulation.ShowSensors",
    Speed: "Simulation.Speed",
    SpeedLabel: "Simulation.SpeedLabel",
    SpeedMap: "Simulation.SpeedMap",
    SpeedSettings: "Simulation.SpeedSettings",
    Start: "Simulation.Start",
    StartAction: "Simulation.StartAction",
    StartFailed: "Simulation.StartFailed",
    Status: "Simulation.Status",
    StatusLabel: "Simulation.StatusLabel",
    Step: "Simulation.Step",
    StepHint: "Simulation.StepHint",
    StepsPerSecond: "Simulation.StepsPerSecond",
    Stop: "Simulation.Stop",
    StopAction: "Simulation.StopAction",
    Stopped: "Simulation.Stopped",
    StreetPositions: "Simulation.StreetPositions",
    TargetSpeed: "Simulation.TargetSpeed",
    Units: "Simulation.Units",
    Unlimited: "Simulation.Unlimited",
    UnlimitedOption: "Simulation.UnlimitedOption",
    WebGpuUnavailable: "Simulation.WebGpuUnavailable",
    ZoneRequired: "Simulation.ZoneRequired",
  },
  Statistics: {
    AllCharts: "Statistics.AllCharts",
    AverageDensity: "Statistics.AverageDensity",
    AverageSpeed: "Statistics.AverageSpeed",
    Bottleneck: "Statistics.Bottleneck",
    ChartKey: "Statistics.ChartKey",
    CohortDescription: "Statistics.CohortDescription",
    CohortDuration: "Statistics.CohortDuration",
    CohortTitle: "Statistics.CohortTitle",
    Cohorts: "Statistics.Cohorts",
    CompletedCohorts: "Statistics.CompletedCohorts",
    Critical: "Statistics.Critical",
    DensityAxis: "Statistics.DensityAxis",
    DensityBand: "Statistics.DensityBand",
    DensityDescription: "Statistics.DensityDescription",
    DensityLegend: "Statistics.DensityLegend",
    DensitySummary: "Statistics.DensitySummary",
    DensityTitle: "Statistics.DensityTitle",
    DensityUnit: "Statistics.DensityUnit",
    Evacuated: "Statistics.Evacuated",
    EvacuatedLabel: "Statistics.EvacuatedLabel",
    Freeflow: "Statistics.Freeflow",
    Jam: "Statistics.Jam",
    Label: "Statistics.Label",
    MeanSpeed: "Statistics.MeanSpeed",
    MeanSpeedLabel: "Statistics.MeanSpeedLabel",
    NoData: "Statistics.NoData",
    OpenHint: "Statistics.OpenHint",
    PeakDensityLabel: "Statistics.PeakDensityLabel",
    PopulationCohort: "Statistics.PopulationCohort",
    Queue: "Statistics.Queue",
    ReferenceThresholds: "Statistics.ReferenceThresholds",
    ResetPosition: "Statistics.ResetPosition",
    SimulationTime: "Statistics.SimulationTime",
    SpeedAxis: "Statistics.SpeedAxis",
    SpeedDescription: "Statistics.SpeedDescription",
    SpeedLegend: "Statistics.SpeedLegend",
    SpeedProfile: "Statistics.SpeedProfile",
    SpeedTitle: "Statistics.SpeedTitle",
    StandardDeviation: "Statistics.StandardDeviation",
    StartHint: "Statistics.StartHint",
    TimeAxis: "Statistics.TimeAxis",
    TimeLabel: "Statistics.TimeLabel",
    Title: "Statistics.Title",
  },
  Tour: {
    Back: "Tour.Back",
    BlockadeBody: "Tour.BlockadeBody",
    BlockadeTitle: "Tour.BlockadeTitle",
    CircleBody: "Tour.CircleBody",
    CircleTitle: "Tour.CircleTitle",
    Close: "Tour.Close",
    ControlsBody: "Tour.ControlsBody",
    ControlsTitle: "Tour.ControlsTitle",
    Done: "Tour.Done",
    EvacuationBody: "Tour.EvacuationBody",
    EvacuationTitle: "Tour.EvacuationTitle",
    Next: "Tour.Next",
    PolygonBody: "Tour.PolygonBody",
    PolygonTitle: "Tour.PolygonTitle",
    Progress: "Tour.Progress",
    RemoveBody: "Tour.RemoveBody",
    RemoveTitle: "Tour.RemoveTitle",
    Replay: "Tour.Replay",
    SafeBody: "Tour.SafeBody",
    SafeTitle: "Tour.SafeTitle",
    SettingsBody: "Tour.SettingsBody",
    SettingsTitle: "Tour.SettingsTitle",
    SimulationBody: "Tour.SimulationBody",
    SimulationTitle: "Tour.SimulationTitle",
    WelcomeBody: "Tour.WelcomeBody",
    WelcomeTitle: "Tour.WelcomeTitle",
    ZoneBody: "Tour.ZoneBody",
    ZoneTitle: "Tour.ZoneTitle",
  },
} as const;
type Domains = typeof TextKeys;
export type TextKey = {
  [D in keyof Domains]: Domains[D][keyof Domains[D]];
}[keyof Domains];
export const englishText: Record<TextKey, string> = {
  "Appearance.Dark": "Dark",
  "Appearance.Language": "Language",
  "Appearance.Light": "Light",
  "Appearance.System": "System",
  "Appearance.Theme": "Theme",
  "Census.Attribution": "Source: GUS, 2021 census",
  "Census.CustomCount": "Custom count",
  "Census.DrawingHint":
    "You can continue drawing while the census estimate loads.",
  "Census.Estimate": "Estimated residents",
  "Census.GridResidents": "GUS 125m grid · Residents: {0}",
  "Census.LoadFailed": "Census data could not be loaded for this zone.",
  "Census.Loading": "Loading population data...",
  "Census.Population": "Census population",
  "Census.Source": "Population source:",
  "Census.SourcePopulation": "GUS NSP 2021 (population: {0})",
  "Census.Unavailable": "Population unavailable",
  "Census.Wait": "Population data is still loading. Try again shortly.",
  "Common.ApiError": "Could not connect to the API: {0}",
  "Common.Cancel": "Cancel",
  "Common.Close": "Close",
  "Common.Collapse": "Collapse",
  "Common.CommunicationError": "Communication error: {0}",
  "Common.Copied": "Copied",
  "Common.Copy": "Copy",
  "Common.DismissError": "Dismiss error",
  "Common.Error": "An error has occurred.",
  "Common.ErrorDetails": "Error: {0}",
  "Common.Expand": "Expand",
  "Common.HoursAgo": "{0} h ago",
  "Common.JustNow": "just now",
  "Common.Loading": "Loading",
  "Common.Maximize": "Maximize",
  "Common.Minimize": "Minimize",
  "Common.MinutesAgo": "{0} min ago",
  "Common.Open": "Open",
  "Common.Optional": "(Optional)",
  "Common.Refresh": "Refresh",
  "Common.Reload": "Reload",
  "Common.Remove": "Remove",
  "Common.Restore": "Restore",
  "Common.Retry": "Try again",
  "Common.Save": "Save",
  "Common.UnhandledError": "An unhandled error has occurred.",
  "Common.View": "View",
  "Common.ViewFailed": "Failed to initialize view: {0}",
  "Demo.BackupShelter": "Backup shelter (Planty)",
  "Demo.Coordinates": "GPS coordinates · Kraków",
  "Demo.Description":
    "Real-world coordinates (metres) · Potential field + social forces · Weidmann and Seyfried",
  "Demo.EastExit": "Main exit (East)",
  "Demo.Exit": "Exit",
  "Demo.MainExit": "Main exit",
  "Demo.MainShelter": "Main shelter (Park Krakowski)",
  "Demo.NorthAssembly": "North assembly point (Park Krakowski)",
  "Demo.NorthShelter": "North shelter (Gate A)",
  "Demo.SampleData": "SAMPLE DATA (MAP)",
  "Demo.SouthAssembly": "South assembly point (Planty)",
  "Demo.SouthShelter": "South shelter (Gate B)",
  "Demo.Title": "Metric crowd simulator",
  "Direction.East": "E (East)",
  "Direction.North": "N (North)",
  "Direction.NorthEast": "NE (North-east)",
  "Direction.NorthWest": "NW (North-west)",
  "Direction.South": "S (South)",
  "Direction.SouthEast": "SE (South-east)",
  "Direction.SouthWest": "SW (South-west)",
  "Direction.West": "W (West)",
  "Drawing.BlockadeEnd": "Click to set end of blockade",
  "Drawing.BlockadeStart": "Click map to set start of Blockade",
  "Drawing.Cancel": "Cancel (Esc)",
  "Drawing.Category": "Drawing category",
  "Drawing.Circle": "Circle",
  "Drawing.Done": "Done",
  "Drawing.EvacuationCenter": "Click map to place center of Evacuation Zone",
  "Drawing.EvacuationPolygon":
    "Click points on the map to draw an evacuation zone",
  "Drawing.EvacuationZone": "Evacuation zone",
  "Drawing.FirstPoint": "First point added. Click to add the second",
  "Drawing.Instructions": "Drawing instructions",
  "Drawing.Navigate": "Navigate",
  "Drawing.Polygon": "Polygon",
  "Drawing.PolygonAdded": "Polygon added. Add more points or click Done",
  "Drawing.PolygonMinimum": "A polygon zone requires at least 3 points.",
  "Drawing.PolygonVertices":
    "Polygon added ({0} vertices). Add more points or click Done",
  "Drawing.RadiusHint": "Move cursor to set radius, click to confirm",
  "Drawing.SafeCenter": "Click map to place center of Safe Zone",
  "Drawing.SafePolygon": "Click points on the map to draw a safe zone",
  "Drawing.SecondPoint":
    "Second point added. Click to add the third and create the polygon",
  "Drawing.Shape": "Shape",
  "Drawing.ShapeHint": "Click on the map to define shape",
  "Drawing.StartHint":
    "Use an evacuation polygon or circle to draw an evacuation zone on the map.",
  "Drawing.Tools": "Map drawing tools",
  "Evacuation.ActiveSession": "● Active session:",
  "Evacuation.Analyzing": "Analyzing occupancy, distance, and road blockades",
  "Evacuation.AssignedShelter": "Your assigned shelter",
  "Evacuation.Assigning": "Assigning a shelter...",
  "Evacuation.Description": "Find your assigned shelter and route",
  "Evacuation.Direction": "Walking direction",
  "Evacuation.GoogleMaps": "Walking directions in Google Maps",
  "Evacuation.Heading": "Your evacuation route",
  "Evacuation.Introduction":
    "Set your location, check your assigned shelter, and start navigation.",
  "Evacuation.Loading": "Loading evacuation plan...",
  "Evacuation.LoadingDetails":
    "Loading session parameters, shelters, and blockades",
  "Evacuation.NoAssignment": "No shelter assigned.",
  "Evacuation.OutsideDescription":
    "Your marked location is outside the evacuation zone. Shelter assignments are available only within this zone. If the location is incorrect, change it on the map.",
  "Evacuation.OutsideTitle": "Outside the evacuation zone",
  "Evacuation.PageTitle": "PlanSafe · Evacuation assistant",
  "Evacuation.Plan": "Evacuation plan",
  "Evacuation.Refresh": "Refresh assignment",
  "Evacuation.RouteInstructions":
    "Mark your location inside the evacuation zone to find a route to your assigned shelter.",
  "Evacuation.Routing": "Finding a route...",
  "Evacuation.Session": "SESSION: {0}",
  "Evacuation.SessionExpired":
    "The evacuation session has expired or is inactive. Contact emergency services.",
  "Evacuation.SessionId": "Active evacuation session ID",
  "Evacuation.SessionLabel": "Session",
  "Evacuation.Start": "Start evacuation",
  "Evacuation.Title": "Evacuation assistant",
  "Evacuation.WalkingTime": "~{0} min on foot",
  "Evacuation.ZoneRequired":
    "Draw at least one evacuation zone before starting an evacuation.",
  "Location.Acquired": "GPS location acquired.",
  "Location.Active": "GPS ACTIVE",
  "Location.BrowserMessage": "Browser message:",
  "Location.Coordinates": "Location coordinates:",
  "Location.Correct": "Correct location",
  "Location.DefaultPosition": "Default zone location (Kraków Main Square)",
  "Location.Denied": "Location access denied.",
  "Location.DismissWarning": "Dismiss location warning",
  "Location.Error": "GPS error.",
  "Location.ErrorTitle": "Location error",
  "Location.Get": "Get GPS location",
  "Location.Getting": "Getting GPS location...",
  "Location.GpsPosition": "Your location (GPS)",
  "Location.HttpsRequired": "GPS access unavailable (HTTPS required)",
  "Location.InsecureConnection":
    "Location access is blocked over HTTP. Use HTTPS or mark your location on the map.",
  "Location.InsecureHost":
    "Location access is blocked on {0} (HTTP). Use HTTPS or localhost.",
  "Location.LocalhostHint": "Location access requires HTTPS or localhost. Open",
  "Location.ManualFallback": "GPS unavailable (mark location on map)",
  "Location.Mark": "Mark location on map",
  "Location.MarkTitle": "Mark your location on the map",
  "Location.NavigationHint":
    "Mark your location inside the evacuation zone to start navigation.",
  "Location.NetworkAcquired": "Location acquired using the network/Wi-Fi.",
  "Location.NotSet": "Location has not been set yet",
  "Location.OrMark": "or mark your location on the map.",
  "Location.PermissionHint":
    "Allow location access in your browser or mark your location on the map.",
  "Location.ProvisionalCoordinates":
    "{0}°N, {1}°E (zone center - verify location)",
  "Location.ProvisionalHint":
    "The route starts near the zone's center. Select your actual location on the map.",
  "Location.Refresh": "Refresh GPS location",
  "Location.SecureHint":
    "Use HTTPS to access GPS, or select your location on the map.",
  "Location.SelectHint": "Click on the map to set your location ·",
  "Location.SelectInZone":
    "Click inside the designated zone on the map to set your location.",
  "Location.SelectedCoordinates": "{0}°N, {1}°E (selected on map)",
  "Location.SelectionMode": "Location selection mode:",
  "Location.Set": "Location set",
  "Location.Timeout": "GPS request timed out.",
  "Location.Unavailable": "Location unavailable (no GPS/network signal).",
  "Location.Unsupported": "This browser does not support GPS geolocation.",
  "Location.Verify": "Verify your location.",
  "Location.YourPosition": "Your location",
  "Map.AssemblyPoint": "Assembly point",
  "Map.Blockade": "Blockade",
  "Map.BlockadeName": "Blockade {0}",
  "Map.BlockadePosition": "Blockade ({0}, {1})",
  "Map.Blockades": "Road blockades",
  "Map.Center": "Center map",
  "Map.CollapseInfo": "Collapse zone information",
  "Map.Contributors": "contributors",
  "Map.EvacuationZone": "Evacuation Zone",
  "Map.EvacuationZoneName": "Evacuation zone {0}",
  "Map.EvacuationZones": "Evacuation zones",
  "Map.ExpandInfo": "Expand zone information",
  "Map.FeatureSummary": "Blockades: {0} · Assembly points: {1}",
  "Map.Features": "Map features",
  "Map.FitShelters": "Fit all shelters in view",
  "Map.GestureHint":
    "Drag to pan · Scroll to zoom · Double-click to reset view",
  "Map.HideZone": "Hide zone map",
  "Map.Length": "Length: {0} m",
  "Map.NoZone": "No evacuation zone drawn.",
  "Map.Radius": "Radius: {0} m",
  "Map.ResetView": "Reset view",
  "Map.SafeLocation": "Safe location",
  "Map.SafeLocations": "Safe havens",
  "Map.SafePoint": "Safe point",
  "Map.SafeZone": "Safe zone",
  "Map.SafeZoneName": "Safe zone {0}",
  "Map.Vertices": "Vertices: {0}",
  "Map.ZoneInfo": "Zone information",
  "Map.ZoomIn": "Zoom in",
  "Map.ZoomOut": "Zoom out",
  "Navigation.Demo": "Simulation Demo (debug)",
  "Navigation.DemoTitle": "Simulation Demo (debug) - PlanSafe",
  "Navigation.Label": "Application navigation",
  "Navigation.Map": "Map",
  "Navigation.MapTitle": "Map - PlanSafe",
  "Navigation.Menu": "Navigation and appearance menu",
  "Navigation.NotFound": "Not found",
  "Navigation.NotFoundDescription": "Page not found.",
  "Navigation.Simulator": "Simulator",
  "Publish.Address": "Evacuation assistant address:",
  "Publish.AssemblyPoints": "ASSEMBLY POINTS",
  "Publish.Blockades": "ROAD BLOCKADES",
  "Publish.ChangeSettings": "Change settings",
  "Publish.CitizenView": "Citizen view:",
  "Publish.CloseProjector": "Close projector",
  "Publish.CodeLabel": "Session code",
  "Publish.CopyFailed":
    "Could not copy the link. Select the address above and copy it manually.",
  "Publish.CopyLink": "Copy link",
  "Publish.CopySuccess": "Link copied. You can now share it.",
  "Publish.Description":
    "Publish the plan to get a link and QR code. People can scan the code to find their assigned shelter and route in a browser.",
  "Publish.HttpError": "Failed to publish plan: HTTP {0}",
  "Publish.LinkCopied": "Link copied",
  "Publish.LinkLabel": "Evacuation plan link",
  "Publish.NextPerson": "Evacuate next person",
  "Publish.OpenHint": "Open the plan in a browser.",
  "Publish.Plan": "Publish plan",
  "Publish.Projector": "Projector",
  "Publish.ProjectorHint": "Toggle projector / large screen mode",
  "Publish.ProjectorTitle": "Evacuation plan",
  "Publish.Publishing": "Publishing...",
  "Publish.PublishingPlan": "Publishing plan...",
  "Publish.QrLabel": "Evacuation plan QR code",
  "Publish.Ready": "Plan ready to share",
  "Publish.ReviewHint": "Review the scenario and prepare a link for residents.",
  "Publish.Scan": "Scan the code to open the plan",
  "Publish.Scenario": "Your scenario",
  "Publish.SessionCode": "SESSION CODE: {0}",
  "Publish.SettingsDescription": "Shelter allocation and plan sharing",
  "Publish.ShareHint":
    "Share the link or QR code with people in the evacuation zone.",
  "Publish.ShareInstructions":
    "Share the link or QR code with people in the evacuation zone.",
  "Publish.ShareTitle": "Share evacuation plan",
  "Publish.Submit": "Publish plan",
  "Publish.Success": "Evacuation plan published",
  "Publish.Summary": "Shelters: {0} · Blockades: {1} · Map width: {2} m",
  "Publish.Title": "Publish evacuation plan",
  "Publish.Zones": "ALARM ZONES",
  "Scenario.Actions": "Scenario actions",
  "Scenario.Active": "Active",
  "Scenario.Branch": "Branch",
  "Scenario.BranchCurrent": "Create branch from current scenario",
  "Scenario.BranchFrom": "Create branch from this scenario",
  "Scenario.BranchName": "Branch name",
  "Scenario.ClearFilter": "Clear branch filter",
  "Scenario.CopyDescription":
    "Edit the copied zones and blockades without changing the parent branch.",
  "Scenario.CopyFeatures": "Copy zones and blockades",
  "Scenario.CopyTree": "Copy scenario tree as JSON",
  "Scenario.Count": "Scenarios: {0}",
  "Scenario.CreateAndSwitch": "Create and switch",
  "Scenario.CreateDescription":
    "Create a branch to test alternative evacuation settings",
  "Scenario.CreateTitle": "Create scenario branch",
  "Scenario.Creating": "Creating branch...",
  "Scenario.Current": "Current",
  "Scenario.Delete": "Delete branch",
  "Scenario.DeleteConfirm": "Delete branch '{0}'?",
  "Scenario.DeleteNamed": "Delete branch {0}",
  "Scenario.Description": "Scenario description",
  "Scenario.DescriptionHint": "What does this scenario test?",
  "Scenario.FeatureSummary":
    "Evacuation zones: {0} · Safe locations: {1} · Blockades: {2}",
  "Scenario.Features": "Active scenario features:",
  "Scenario.Filter": "Filter branches",
  "Scenario.FilterHint": "Filter branches...",
  "Scenario.Label": "Scenario",
  "Scenario.Loading": "Loading scenario graph...",
  "Scenario.NameExample": "e.g. scenario/bridge-closure, test/florian-blockade",
  "Scenario.NamePlaceholder": "scenario/my-hypothesis",
  "Scenario.NameRequired": "Enter a branch name (e.g. scenario/new-blockade).",
  "Scenario.NewBranch": "New branch",
  "Scenario.NoMatches": "No matching branches found.",
  "Scenario.OpenTree": "Open scenario tree: {0}",
  "Scenario.Parent": "Branching from:",
  "Scenario.Root": "Root",
  "Scenario.Session": "Session: {0}",
  "Scenario.Switch": "Switch",
  "Scenario.SwitchHint": "Switch to this scenario",
  "Scenario.Tree": "Scenario tree",
  "Scenario.TreeCopied": "Scenario tree copied as JSON.",
  "Shelter.Allocation": "Shelter allocation",
  "Shelter.AllocationTitle": "Shelter allocation",
  "Shelter.Criterion": "Shelter allocation criterion:",
  "Shelter.DecreaseDistance": "Decrease distance weight",
  "Shelter.DecreaseOccupancy": "Decrease occupancy weight",
  "Shelter.DefaultName": "Evacuation shelter",
  "Shelter.Distance": "Distance",
  "Shelter.DistanceArrow": "← Distance",
  "Shelter.DistanceLabel": "Distance weight:",
  "Shelter.DistanceOnly": "Distance only (100% weight)",
  "Shelter.DistancePercent": "{0}% distance",
  "Shelter.DistanceValue": "Distance weight: {0}",
  "Shelter.DistanceWeight": "Distance weight",
  "Shelter.Full": "Full",
  "Shelter.IncreaseDistance": "Increase distance weight",
  "Shelter.IncreaseOccupancy": "Increase occupancy weight",
  "Shelter.Label": "Shelter",
  "Shelter.Occupancy": "Occupancy",
  "Shelter.OccupancyArrow": "Occupancy →",
  "Shelter.OccupancyLabel": "Occupancy weight:",
  "Shelter.OccupancyLabelAccessible": "Shelter occupancy",
  "Shelter.OccupancyOnly": "Occupancy only (100% weight)",
  "Shelter.OccupancyPercent": "{0}% occupancy",
  "Shelter.OccupancySummary": "Occupancy: {0} / {1} ({2}%)",
  "Shelter.OccupancyValue": "Occupancy weight: {0}",
  "Shelter.OccupancyWeight": "Occupancy weight",
  "Shelter.Places": "{0} / {1} places",
  "Shelter.PresetA": "Scenario A (1:0)",
  "Shelter.PresetB": "Scenario B (0.5:0.5)",
  "Shelter.PresetC": "Scenario C (0.2:0.8)",
  "Shelter.Presets": "Presets:",
  "Shelter.ResetOccupancy": "Reset occupancy",
  "Shelter.SelectHint": "Click to select this shelter",
  "Shelter.WeightsLabel": "Distance / occupancy weights:",
  "Shelter.WeightsValue": "Distance / occupancy weights: {0}% / {1}%",
  "Simulation.ActualSpeed": "Actual speed: {0}× ({1})",
  "Simulation.AgentCount": "Number of agents",
  "Simulation.AgentCountLabel": "Agents:",
  "Simulation.AgentCountValue": "Agents: {0}",
  "Simulation.AgentPerDotUnit": "agent per dot",
  "Simulation.AgentPositions": "Agents",
  "Simulation.AgentSpeed": "Speed",
  "Simulation.AgentSummary": "Active agents: {0} (Evacuated: {1})",
  "Simulation.AgentViewHint": "Individuals (agents on the map)",
  "Simulation.Agents": "Agents",
  "Simulation.AgentsPerDot": "Agents per dot",
  "Simulation.AgentsPerDotLabel": "Agents per dot:",
  "Simulation.AgentsPerDotUnit": "agents per dot",
  "Simulation.AgentsPerDotValue": "Agents per dot: {0}",
  "Simulation.ChangeSpeed": "Click to change simulation speed",
  "Simulation.Close": "Close simulation",
  "Simulation.CloseHint": "End simulation and return to map editing",
  "Simulation.Completed": "Completed",
  "Simulation.Controls": "Simulation controls",
  "Simulation.Coordinates":
    "Map layer: Coordinates in metres [0, {0}] × [0, {1}]",
  "Simulation.Current": "Current simulation",
  "Simulation.Defaults": "Restore defaults",
  "Simulation.Density": "Density",
  "Simulation.DensityMap": "Density map",
  "Simulation.DestinationRequired":
    "Draw at least one safe location as an evacuation destination.",
  "Simulation.Diagnostics": "Show diagnostics",
  "Simulation.Dimensions": "Simulation dimensions",
  "Simulation.DimensionsValue": "Simulation dimensions: {0} m × {1} m",
  "Simulation.DismissMessage": "Dismiss simulation message",
  "Simulation.DisplayMode": "Display mode",
  "Simulation.DisplayRefresh": "Match display",
  "Simulation.DisplayRefreshOption": "Match display",
  "Simulation.DisplaySettings": "Display mode and sensors",
  "Simulation.DotCount": "Simulated dots: {0}",
  "Simulation.Elapsed": "Elapsed time",
  "Simulation.Ended": "SIMULATION ENDED",
  "Simulation.Engine": "Computation engine",
  "Simulation.EngineHint": "Simulation computation engine",
  "Simulation.Evacuated": "Evacuated",
  "Simulation.EvacuatedProgress": "/ {0} evacuated ({1}%)",
  "Simulation.Evacuation": "Evacuation",
  "Simulation.FlowParticles": "Flow particles (field vectors)",
  "Simulation.FpsLimit": "FPS limit",
  "Simulation.Live": "LIVE SIMULATION",
  "Simulation.LoadingParameters": "Loading parameters...",
  "Simulation.MapDisplay": "Map view",
  "Simulation.MaxAgentsPerDot": "25 agents per dot",
  "Simulation.OneAgentPerDot": "1 agent per dot",
  "Simulation.OpenSettings": "Open simulation settings",
  "Simulation.Parameters": "Simulation parameters",
  "Simulation.Pause": "Pause",
  "Simulation.PauseHint": "Pause simulation (Space)",
  "Simulation.Paused": "Paused",
  "Simulation.PhysicsDescription":
    "Crowd physics: Weidmann diagram (density-speed) · Leader-follower asymmetry",
  "Simulation.PopulationSettings": "Population and agents",
  "Simulation.Preparing": "Preparing...",
  "Simulation.RayLength": "Ray length",
  "Simulation.RayLengthLabel": "Ray length:",
  "Simulation.RealTime": "1× (real time)",
  "Simulation.RenderFps": "Render FPS: {0}",
  "Simulation.Repulsion": "Repulsion",
  "Simulation.RepulsionLabel": "Repulsion:",
  "Simulation.RepulsionValue": "Repulsion: {0}",
  "Simulation.Reset": "Reset",
  "Simulation.ResetAgents": "Reset agents",
  "Simulation.ResetHint": "Return agents to their starting positions",
  "Simulation.ResumeHint": "Resume simulation (Space)",
  "Simulation.Run": "Run",
  "Simulation.Running": "Running",
  "Simulation.SensorHint": "Directional sensor rays",
  "Simulation.Sensors": "Sensors",
  "Simulation.Settings": "Simulation settings",
  "Simulation.SettingsDescription":
    "Set crowd behaviour, shelter allocation, and map display",
  "Simulation.SettingsTitle": "Simulation settings",
  "Simulation.ShowSensors": "Show sensor rays",
  "Simulation.Speed": "Speed",
  "Simulation.SpeedLabel": "Speed:",
  "Simulation.SpeedMap": "Speed map",
  "Simulation.SpeedSettings": "Speed and FPS",
  "Simulation.Start": "Start",
  "Simulation.StartAction": "Start simulation",
  "Simulation.StartFailed": "Failed to start simulation: {0}",
  "Simulation.Status": "Simulation status",
  "Simulation.StatusLabel": "Status:",
  "Simulation.Step": "Step",
  "Simulation.StepHint": "One step forward (16 ms)",
  "Simulation.StepsPerSecond": "Simulation steps/s: {0}",
  "Simulation.Stop": "Stop",
  "Simulation.StopAction": "Stop simulation",
  "Simulation.Stopped": "Stopped",
  "Simulation.StreetPositions": "Agents",
  "Simulation.TargetSpeed": "Target: {0}",
  "Simulation.Units":
    "Metric units: Agent radius ~{0} m · Speed ~1.4 m/s (5.0 km/h)",
  "Simulation.Unlimited": "Unlimited",
  "Simulation.UnlimitedOption": "Unlimited",
  "Simulation.WebGpuUnavailable": "WebGPU is unavailable in this browser",
  "Simulation.ZoneRequired":
    "Draw at least one evacuation zone before starting the simulation.",
  "Statistics.AllCharts": "All statistics (grid)",
  "Statistics.CohortDescription":
    "Evacuation time by ten percent population cohort",
  "Statistics.CohortDuration": "Cohort duration (min)",
  "Statistics.CohortTitle":
    "1. Evacuation time by cohort (each 10% of population)",
  "Statistics.Cohorts": "Cohorts (10%)",
  "Statistics.CompletedCohorts": "Completed cohorts: {0}/10 ({1}%)",
  "Statistics.DensityAxis": "Density [people/m²]",
  "Statistics.DensityBand": "Crowd density (μ ± σ)",
  "Statistics.DensityDescription":
    "Crowd density profile with standard deviation",
  "Statistics.DensityLegend":
    "Band: μ ± σ · Line: μ(t) · Free flow 0.5 people/m² · Queue 2.0 people/m² · Critical 3.5 people/m²",
  "Statistics.DensitySummary": "MEAN / PEAK DENSITY",
  "Statistics.DensityTitle": "3. Average Crowd Density Over Time",
  "Statistics.DensityUnit": "people/m²",
  "Statistics.Evacuated": "EVACUATED",
  "Statistics.EvacuatedLabel": "EVACUATED:",
  "Statistics.Label": "Statistics",
  "Statistics.MeanSpeed": "MEAN SPEED",
  "Statistics.MeanSpeedLabel": "MEAN SPEED:",
  "Statistics.OpenHint": "Open live charts and statistics",
  "Statistics.PeakDensityLabel": "PEAK DENSITY:",
  "Statistics.PopulationCohort": "Population cohort",
  "Statistics.ResetPosition": "Reset window position",
  "Statistics.SimulationTime": "SIMULATION TIME",
  "Statistics.SpeedAxis": "Speed [m/s]",
  "Statistics.SpeedDescription":
    "Agent mean speed profile with standard deviation",
  "Statistics.SpeedLegend":
    "Band: μ ± σ · Line: μ(t) · Free flow > 1.1 m/s · Bottleneck 0.6 m/s · Jam < 0.2 m/s",
  "Statistics.SpeedProfile": "Speed profile",
  "Statistics.SpeedTitle": "2. Average Agent Speed Over Time",
  "Statistics.TimeAxis": "Time elapsed since alarm [s]",
  "Statistics.TimeLabel": "TIME:",
  "Statistics.Title": "Analytics and statistics",
  "EvacuationUi.PageTitle": "Evacuation - PlanSafe",
  "EvacuationUi.Appearance": "Appearance",
  "EvacuationUi.LoadingLabel": "Loading evacuation",
  "EvacuationUi.Loading": "Loading shelters and the evacuation zone...",
  "EvacuationUi.PlanUnavailable": "Evacuation plan unavailable",
  "EvacuationUi.RefreshPage": "Refresh page",
  "EvacuationUi.MapLabel": "Evacuation zone map",
  "EvacuationUi.MapSelectLabel":
    "Map: select your location inside the evacuation zone",
  "EvacuationUi.MapTools": "Map tools",
  "EvacuationUi.FitHint": "Show the entire zone and shelters",
  "EvacuationUi.Fit": "Fit map",
  "EvacuationUi.Legend": "Legend",
  "EvacuationUi.FullShelter": "Full shelter",
  "EvacuationUi.Information": "Evacuation information",
  "EvacuationUi.YourShelter": "Your shelter",
  "EvacuationUi.Details": "Details",
  "EvacuationUi.Dismiss": "Dismiss",
  "EvacuationUi.CorrectionHint":
    "Select your location inside the zone on the map.",
  "EvacuationUi.CancelCorrection": "Cancel location correction",
  "EvacuationUi.NotSet": "Your location has not been set.",
  "EvacuationUi.RefreshGps": "Refresh GPS",
  "EvacuationUi.UseGps": "Use GPS",
  "EvacuationUi.SelectMap": "Select on map",
  "EvacuationUi.HideMap": "Hide map",
  "EvacuationUi.ShowMap": "Show map",
  "EvacuationUi.LocationHelp": "Location help",
  "EvacuationUi.PreviewHint":
    "The route currently starts at the zone center, not your confirmed location.",
  "EvacuationUi.PickHint":
    "Select your actual location inside the shaded evacuation zone.",
  "EvacuationUi.SelectMyLocation": "Select my location on the map",
  "EvacuationUi.FindingLocation": "Finding location...",
  "EvacuationUi.RetryGps": "Retry GPS",
  "EvacuationUi.Assignment": "Shelter assignment",
  "EvacuationUi.Navigate": "Navigate in Google Maps",
  "EvacuationUi.NewTab": "(opens a new tab)",
  "EvacuationUi.Direction": "Direction to shelter",
  "EvacuationUi.BearingHint":
    "Geographic bearing. Check the walking route in navigation.",
  "EvacuationUi.FindingShelter": "Finding a shelter...",
  "EvacuationUi.Checking": "Checking distance, occupancy, and roadblocks.",
  "EvacuationUi.Where": "Where are you?",
  "EvacuationUi.LocationHint":
    "Use GPS or select your location inside the zone on the map.",
  "EvacuationUi.Outside": "Your location is outside the evacuation zone.",
  "EvacuationUi.CorrectMap": "Correct your location on the map",
  "EvacuationUi.NoShelter": "No available shelter",
  "EvacuationUi.NoAssignment":
    "No shelter assignment is available for your location.",
  "EvacuationUi.LoadError":
    "The evacuation plan could not be loaded. Refresh the page to try again.",
  "EvacuationUi.WrongPlan":
    "This evacuation link no longer matches the published plan. Ask the organizer for a current link.",
  "EvacuationUi.Expired":
    "The evacuation session has expired. Contact the emergency services for current information.",
  "EvacuationUi.GpsDenied":
    "Location access is blocked. Allow location access in your browser's site settings, then retry GPS, or select your location on the map.",
  "EvacuationUi.GpsTimeout":
    "Finding your location took too long. Retry GPS or select your location on the map.",
  "EvacuationUi.GpsUnavailable":
    "Your device could not determine your location. Check that location services are on, or select your location on the map.",
  "EvacuationUi.GpsInsecure":
    "GPS requires a secure HTTPS connection. Select your location on the map to continue.",
  "EvacuationUi.GpsUnsupported":
    "This browser does not support GPS. Select your location on the map to continue.",
  "EvacuationUi.GpsError":
    "Your location could not be retrieved. Retry GPS or select your location on the map.",
  "EvacuationUi.WalkingTime": "about {0} min on foot",
  "EvacuationUi.Places": "{0} / {1} spaces",
  "EvacuationUi.SelectedCoordinates": "{0}°N, {1}°E (selected on the map)",
  "EvacuationUx.ExpandPanel": "Expand evacuation information",
  "EvacuationUx.CollapsePanel": "Collapse evacuation information",
  "EvacuationUx.ConfirmLocation": "Confirm your location",
  "EvacuationUx.PickOnMap": "Select your location on the map",
  "EvacuationUx.PickInside": "Choose a point inside the zone",
  "EvacuationUx.GpsConfirmed": "Located using GPS",
  "EvacuationUx.MapConfirmed": "Location selected on map",
  "EvacuationUx.ChangeLocation": "Change location",
  "EvacuationUx.ShelterDetails": "Shelter details",
  "EvacuationUx.OutsideHint":
    "Your location is outside this evacuation zone. Select a point inside the shaded area.",
  "EvacuationUx.GpsPending":
    "Finding your location. You can also select it on the map.",
  "EvacuationUx.LocationHint":
    "Select where you are to find a route to a shelter.",
  "EvacuationUx.GpsDenied":
    "Location access is blocked. Select on the map, or allow location in your browser settings and retry.",
  "EvacuationUx.GpsTimeout":
    "GPS is taking too long. Select your location on the map or try again.",
  "EvacuationUx.GpsUnavailable":
    "GPS could not find your location. Select it on the map or try again.",
  "EvacuationUx.GpsInsecure":
    "GPS needs HTTPS. Select your location on the map to continue.",
  "EvacuationUx.GpsUnsupported":
    "GPS is not supported in this browser. Select your location on the map.",
  "EvacuationUx.GpsError":
    "Location could not be retrieved. Select it on the map or retry GPS.",
  "Shelter.PeopleCount": "{0} people",
  "Shelter.PeopleHere": "People currently here",
  "Statistics.AverageSpeed": "Average speed (mean)",
  "Statistics.AverageDensity": "Average density (mean)",
  "Statistics.Freeflow": "Free flow",
  "Statistics.Bottleneck": "Bottleneck",
  "Statistics.Jam": "Jam",
  "Statistics.Queue": "Queue",
  "Statistics.Critical": "Critical",
  "Statistics.NoData": "NO DATA",
  "Statistics.StartHint": "Start a simulation to see statistics.",
  "Statistics.ChartKey": "Chart key",
  "Statistics.StandardDeviation": "Mean +/- 1 standard deviation",
  "Statistics.ReferenceThresholds": "Reference thresholds",
  "Tour.Replay": "Map tour",
  "Tour.Next": "Next",
  "Tour.Back": "Back",
  "Tour.Done": "Start planning",
  "Tour.Close": "Close tour",
  "Tour.Progress": "{{current}} of {{total}}",
  "Tour.WelcomeTitle": "Plan a safe evacuation with PlanSafe",
  "Tour.WelcomeBody":
    "Define evacuation areas, choose safe destinations and mark blocked routes. Test how people reach safety, then share your plan.",
  "Tour.ZoneTitle": "1. Where are people leaving?",
  "Tour.ZoneBody":
    "Evacuation zones are areas people need to leave. Choose the “Evacuation zone” tool, then Polygon or Circle. The number of residents comes from census data for these zones. You can set a custom number in Settings; we'll show you where to find them shortly.",
  "Tour.SafeTitle": "2. Where should they go?",
  "Tour.SafeBody":
    "Safe locations are destinations for evacuees. Use this green tool to draw a polygon or circle. Add a reachable safe location to give people somewhere to go.",
  "Tour.BlockadeTitle": "3. Mark blocked passages",
  "Tour.BlockadeBody":
    "Blockades are line barriers that people must avoid. Select Blockade, click the start of the barrier on the map, then click its end. Use them to represent closed streets or inaccessible passages.",
  "Tour.PolygonTitle": "Draw a polygon",
  "Tour.PolygonBody":
    "Choose Evacuation zone or Safe location, then Polygon. Click at least three corners on the map: the third creates the area. Keep clicking to add corners, then choose Done to finish.",
  "Tour.CircleTitle": "Draw a circle in two clicks",
  "Tour.CircleBody":
    "Choose Evacuation zone or Safe location, then Circle. Click once to place the centre, move the pointer to set the radius, then click again to confirm. On touch screens, tap the centre and then the edge.",
  "Tour.RemoveTitle": "Remove an element",
  "Tour.RemoveBody":
    "Switch to Navigate, then click a zone, safe location or blockade on the map. Its popup shows the element details and a Remove button.",
  "Tour.SettingsTitle": "Tune your scenario",
  "Tour.SettingsBody":
    "Configuration lets you choose census data or a custom population, simulation speed and frame rate. Balance distance against shelter occupancy when assigning destinations, and switch between people, speed and density views.",
  "Tour.SimulationTitle": "Test your plan",
  "Tour.SimulationBody":
    "This button runs the crowd movement model using your zones, safe locations, blockades and settings. First, add an evacuation zone and a safe destination. Watch movement and evacuation progress; you can pause playback, change its speed and inspect statistics. You can adjust map elements and settings and run the simulation as many times as you need.",
  "Tour.EvacuationTitle": "Share the evacuation plan",
  "Tour.EvacuationBody":
    "Start evacuation opens a review of your plan. From there, Publish plan creates a shareable link and QR code for the citizen view. Opening this button does not publish automatically. Replay this guide any time with Map tour.",
  "Tour.ControlsTitle": "Simulation controls",
  "Tour.ControlsBody":
    "This panel lets you control a running simulation. The counter shows elapsed time and evacuation progress. Play/Pause controls playback; Step advances the simulation by one step while paused, and Reset starts the run again. Switch between people, speed and density views. The speed button changes the playback rate, including MAX. The chart opens statistics, and × closes simulation mode and returns to planning.",
};
