// <auto-generated />
using Microsoft.Extensions.Localization;

namespace PlanSafe.App.Localization;

public sealed class LocalizedText(IStringLocalizer<UiStrings> strings)
{
    public AppearanceText Appearance { get; } = new(strings);
    public CensusText Census { get; } = new(strings);
    public CommonText Common { get; } = new(strings);
    public DemoText Demo { get; } = new(strings);
    public DirectionText Direction { get; } = new(strings);
    public DrawingText Drawing { get; } = new(strings);
    public EvacuationText Evacuation { get; } = new(strings);
    public EvacuationUiText EvacuationUi { get; } = new(strings);
    public EvacuationUxText EvacuationUx { get; } = new(strings);
    public LocationText Location { get; } = new(strings);
    public MapText Map { get; } = new(strings);
    public NavigationText Navigation { get; } = new(strings);
    public PublishText Publish { get; } = new(strings);
    public ScenarioText Scenario { get; } = new(strings);
    public ShelterText Shelter { get; } = new(strings);
    public SimulationText Simulation { get; } = new(strings);
    public StatisticsText Statistics { get; } = new(strings);
    public TourText Tour { get; } = new(strings);

    public sealed class AppearanceText(IStringLocalizer<UiStrings> strings)
    {
        public string Dark => strings["Appearance.Dark"].Value;
        public string Language => strings["Appearance.Language"].Value;
        public string Light => strings["Appearance.Light"].Value;
        public string System => strings["Appearance.System"].Value;
        public string Theme => strings["Appearance.Theme"].Value;
    }

    public sealed class CensusText(IStringLocalizer<UiStrings> strings)
    {
        public string Attribution => strings["Census.Attribution"].Value;
        public string CustomCount => strings["Census.CustomCount"].Value;
        public string DrawingHint => strings["Census.DrawingHint"].Value;
        public string Estimate => strings["Census.Estimate"].Value;
        public string GridResidents(object arg0) => strings["Census.GridResidents", arg0].Value;
        public string LoadFailed => strings["Census.LoadFailed"].Value;
        public string Loading => strings["Census.Loading"].Value;
        public string Population => strings["Census.Population"].Value;
        public string Source => strings["Census.Source"].Value;
        public string SourcePopulation(object arg0) => strings["Census.SourcePopulation", arg0].Value;
        public string Unavailable => strings["Census.Unavailable"].Value;
        public string Wait => strings["Census.Wait"].Value;
    }

    public sealed class CommonText(IStringLocalizer<UiStrings> strings)
    {
        public string ApiError(object arg0) => strings["Common.ApiError", arg0].Value;
        public string Cancel => strings["Common.Cancel"].Value;
        public string Close => strings["Common.Close"].Value;
        public string Collapse => strings["Common.Collapse"].Value;
        public string CommunicationError(object arg0) => strings["Common.CommunicationError", arg0].Value;
        public string Copied => strings["Common.Copied"].Value;
        public string Copy => strings["Common.Copy"].Value;
        public string DismissError => strings["Common.DismissError"].Value;
        public string Error => strings["Common.Error"].Value;
        public string ErrorDetails(object arg0) => strings["Common.ErrorDetails", arg0].Value;
        public string Expand => strings["Common.Expand"].Value;
        public string HoursAgo(object arg0) => strings["Common.HoursAgo", arg0].Value;
        public string JustNow => strings["Common.JustNow"].Value;
        public string Loading => strings["Common.Loading"].Value;
        public string Maximize => strings["Common.Maximize"].Value;
        public string Minimize => strings["Common.Minimize"].Value;
        public string MinutesAgo(object arg0) => strings["Common.MinutesAgo", arg0].Value;
        public string Open => strings["Common.Open"].Value;
        public string Optional => strings["Common.Optional"].Value;
        public string Refresh => strings["Common.Refresh"].Value;
        public string Reload => strings["Common.Reload"].Value;
        public string Remove => strings["Common.Remove"].Value;
        public string Restore => strings["Common.Restore"].Value;
        public string Retry => strings["Common.Retry"].Value;
        public string Save => strings["Common.Save"].Value;
        public string UnhandledError => strings["Common.UnhandledError"].Value;
        public string View => strings["Common.View"].Value;
        public string ViewFailed(object arg0) => strings["Common.ViewFailed", arg0].Value;
    }

    public sealed class DemoText(IStringLocalizer<UiStrings> strings)
    {
        public string BackupShelter => strings["Demo.BackupShelter"].Value;
        public string Coordinates => strings["Demo.Coordinates"].Value;
        public string Description => strings["Demo.Description"].Value;
        public string EastExit => strings["Demo.EastExit"].Value;
        public string Exit => strings["Demo.Exit"].Value;
        public string MainExit => strings["Demo.MainExit"].Value;
        public string MainShelter => strings["Demo.MainShelter"].Value;
        public string NorthAssembly => strings["Demo.NorthAssembly"].Value;
        public string NorthShelter => strings["Demo.NorthShelter"].Value;
        public string SampleData => strings["Demo.SampleData"].Value;
        public string SouthAssembly => strings["Demo.SouthAssembly"].Value;
        public string SouthShelter => strings["Demo.SouthShelter"].Value;
        public string Title => strings["Demo.Title"].Value;
    }

    public sealed class DirectionText(IStringLocalizer<UiStrings> strings)
    {
        public string East => strings["Direction.East"].Value;
        public string North => strings["Direction.North"].Value;
        public string NorthEast => strings["Direction.NorthEast"].Value;
        public string NorthWest => strings["Direction.NorthWest"].Value;
        public string South => strings["Direction.South"].Value;
        public string SouthEast => strings["Direction.SouthEast"].Value;
        public string SouthWest => strings["Direction.SouthWest"].Value;
        public string West => strings["Direction.West"].Value;
    }

    public sealed class DrawingText(IStringLocalizer<UiStrings> strings)
    {
        public string BlockadeEnd => strings["Drawing.BlockadeEnd"].Value;
        public string BlockadeStart => strings["Drawing.BlockadeStart"].Value;
        public string Cancel => strings["Drawing.Cancel"].Value;
        public string Category => strings["Drawing.Category"].Value;
        public string Circle => strings["Drawing.Circle"].Value;
        public string Done => strings["Drawing.Done"].Value;
        public string EvacuationCenter => strings["Drawing.EvacuationCenter"].Value;
        public string EvacuationPolygon => strings["Drawing.EvacuationPolygon"].Value;
        public string EvacuationZone => strings["Drawing.EvacuationZone"].Value;
        public string FirstPoint => strings["Drawing.FirstPoint"].Value;
        public string Instructions => strings["Drawing.Instructions"].Value;
        public string Navigate => strings["Drawing.Navigate"].Value;
        public string Polygon => strings["Drawing.Polygon"].Value;
        public string PolygonAdded => strings["Drawing.PolygonAdded"].Value;
        public string PolygonMinimum => strings["Drawing.PolygonMinimum"].Value;
        public string PolygonVertices(object arg0) => strings["Drawing.PolygonVertices", arg0].Value;
        public string RadiusHint => strings["Drawing.RadiusHint"].Value;
        public string SafeCenter => strings["Drawing.SafeCenter"].Value;
        public string SafePolygon => strings["Drawing.SafePolygon"].Value;
        public string SecondPoint => strings["Drawing.SecondPoint"].Value;
        public string Shape => strings["Drawing.Shape"].Value;
        public string ShapeHint => strings["Drawing.ShapeHint"].Value;
        public string StartHint => strings["Drawing.StartHint"].Value;
        public string Tools => strings["Drawing.Tools"].Value;
    }

    public sealed class EvacuationText(IStringLocalizer<UiStrings> strings)
    {
        public string ActiveSession => strings["Evacuation.ActiveSession"].Value;
        public string Analyzing => strings["Evacuation.Analyzing"].Value;
        public string AssignedShelter => strings["Evacuation.AssignedShelter"].Value;
        public string Assigning => strings["Evacuation.Assigning"].Value;
        public string Description => strings["Evacuation.Description"].Value;
        public string Direction => strings["Evacuation.Direction"].Value;
        public string GoogleMaps => strings["Evacuation.GoogleMaps"].Value;
        public string Heading => strings["Evacuation.Heading"].Value;
        public string Introduction => strings["Evacuation.Introduction"].Value;
        public string Loading => strings["Evacuation.Loading"].Value;
        public string LoadingDetails => strings["Evacuation.LoadingDetails"].Value;
        public string NoAssignment => strings["Evacuation.NoAssignment"].Value;
        public string OutsideDescription => strings["Evacuation.OutsideDescription"].Value;
        public string OutsideTitle => strings["Evacuation.OutsideTitle"].Value;
        public string PageTitle => strings["Evacuation.PageTitle"].Value;
        public string Plan => strings["Evacuation.Plan"].Value;
        public string Refresh => strings["Evacuation.Refresh"].Value;
        public string RouteInstructions => strings["Evacuation.RouteInstructions"].Value;
        public string Routing => strings["Evacuation.Routing"].Value;
        public string Session(object arg0) => strings["Evacuation.Session", arg0].Value;
        public string SessionExpired => strings["Evacuation.SessionExpired"].Value;
        public string SessionId => strings["Evacuation.SessionId"].Value;
        public string SessionLabel => strings["Evacuation.SessionLabel"].Value;
        public string Start => strings["Evacuation.Start"].Value;
        public string Title => strings["Evacuation.Title"].Value;
        public string WalkingTime(object arg0) => strings["Evacuation.WalkingTime", arg0].Value;
    }

    public sealed class EvacuationUiText(IStringLocalizer<UiStrings> strings)
    {
        public string Appearance => strings["EvacuationUi.Appearance"].Value;
        public string Assignment => strings["EvacuationUi.Assignment"].Value;
        public string BearingHint => strings["EvacuationUi.BearingHint"].Value;
        public string CancelCorrection => strings["EvacuationUi.CancelCorrection"].Value;
        public string Checking => strings["EvacuationUi.Checking"].Value;
        public string CorrectMap => strings["EvacuationUi.CorrectMap"].Value;
        public string CorrectionHint => strings["EvacuationUi.CorrectionHint"].Value;
        public string Details => strings["EvacuationUi.Details"].Value;
        public string Direction => strings["EvacuationUi.Direction"].Value;
        public string Dismiss => strings["EvacuationUi.Dismiss"].Value;
        public string Expired => strings["EvacuationUi.Expired"].Value;
        public string FindingLocation => strings["EvacuationUi.FindingLocation"].Value;
        public string FindingShelter => strings["EvacuationUi.FindingShelter"].Value;
        public string Fit => strings["EvacuationUi.Fit"].Value;
        public string FitHint => strings["EvacuationUi.FitHint"].Value;
        public string FullShelter => strings["EvacuationUi.FullShelter"].Value;
        public string GpsDenied => strings["EvacuationUi.GpsDenied"].Value;
        public string GpsError => strings["EvacuationUi.GpsError"].Value;
        public string GpsInsecure => strings["EvacuationUi.GpsInsecure"].Value;
        public string GpsTimeout => strings["EvacuationUi.GpsTimeout"].Value;
        public string GpsUnavailable => strings["EvacuationUi.GpsUnavailable"].Value;
        public string GpsUnsupported => strings["EvacuationUi.GpsUnsupported"].Value;
        public string HideMap => strings["EvacuationUi.HideMap"].Value;
        public string Information => strings["EvacuationUi.Information"].Value;
        public string Legend => strings["EvacuationUi.Legend"].Value;
        public string LoadError => strings["EvacuationUi.LoadError"].Value;
        public string Loading => strings["EvacuationUi.Loading"].Value;
        public string LoadingLabel => strings["EvacuationUi.LoadingLabel"].Value;
        public string LocationHelp => strings["EvacuationUi.LocationHelp"].Value;
        public string LocationHint => strings["EvacuationUi.LocationHint"].Value;
        public string MapLabel => strings["EvacuationUi.MapLabel"].Value;
        public string MapSelectLabel => strings["EvacuationUi.MapSelectLabel"].Value;
        public string MapTools => strings["EvacuationUi.MapTools"].Value;
        public string Navigate => strings["EvacuationUi.Navigate"].Value;
        public string NewTab => strings["EvacuationUi.NewTab"].Value;
        public string NoAssignment => strings["EvacuationUi.NoAssignment"].Value;
        public string NoShelter => strings["EvacuationUi.NoShelter"].Value;
        public string NotSet => strings["EvacuationUi.NotSet"].Value;
        public string Outside => strings["EvacuationUi.Outside"].Value;
        public string PageTitle => strings["EvacuationUi.PageTitle"].Value;
        public string PickHint => strings["EvacuationUi.PickHint"].Value;
        public string Places(object arg0, object arg1) => strings["EvacuationUi.Places", arg0, arg1].Value;
        public string PlanUnavailable => strings["EvacuationUi.PlanUnavailable"].Value;
        public string PreviewHint => strings["EvacuationUi.PreviewHint"].Value;
        public string RefreshGps => strings["EvacuationUi.RefreshGps"].Value;
        public string RefreshPage => strings["EvacuationUi.RefreshPage"].Value;
        public string RetryGps => strings["EvacuationUi.RetryGps"].Value;
        public string SelectMap => strings["EvacuationUi.SelectMap"].Value;
        public string SelectMyLocation => strings["EvacuationUi.SelectMyLocation"].Value;
        public string SelectedCoordinates(object arg0, object arg1) => strings["EvacuationUi.SelectedCoordinates", arg0, arg1].Value;
        public string ShowMap => strings["EvacuationUi.ShowMap"].Value;
        public string UseGps => strings["EvacuationUi.UseGps"].Value;
        public string WalkingTime(object arg0) => strings["EvacuationUi.WalkingTime", arg0].Value;
        public string Where => strings["EvacuationUi.Where"].Value;
        public string WrongPlan => strings["EvacuationUi.WrongPlan"].Value;
        public string YourShelter => strings["EvacuationUi.YourShelter"].Value;
    }

    public sealed class EvacuationUxText(IStringLocalizer<UiStrings> strings)
    {
        public string ChangeLocation => strings["EvacuationUx.ChangeLocation"].Value;
        public string CollapsePanel => strings["EvacuationUx.CollapsePanel"].Value;
        public string ConfirmLocation => strings["EvacuationUx.ConfirmLocation"].Value;
        public string ExpandPanel => strings["EvacuationUx.ExpandPanel"].Value;
        public string GpsConfirmed => strings["EvacuationUx.GpsConfirmed"].Value;
        public string GpsDenied => strings["EvacuationUx.GpsDenied"].Value;
        public string GpsError => strings["EvacuationUx.GpsError"].Value;
        public string GpsInsecure => strings["EvacuationUx.GpsInsecure"].Value;
        public string GpsPending => strings["EvacuationUx.GpsPending"].Value;
        public string GpsTimeout => strings["EvacuationUx.GpsTimeout"].Value;
        public string GpsUnavailable => strings["EvacuationUx.GpsUnavailable"].Value;
        public string GpsUnsupported => strings["EvacuationUx.GpsUnsupported"].Value;
        public string LocationHint => strings["EvacuationUx.LocationHint"].Value;
        public string MapConfirmed => strings["EvacuationUx.MapConfirmed"].Value;
        public string OutsideHint => strings["EvacuationUx.OutsideHint"].Value;
        public string PickInside => strings["EvacuationUx.PickInside"].Value;
        public string PickOnMap => strings["EvacuationUx.PickOnMap"].Value;
        public string ShelterDetails => strings["EvacuationUx.ShelterDetails"].Value;
    }

    public sealed class LocationText(IStringLocalizer<UiStrings> strings)
    {
        public string Acquired => strings["Location.Acquired"].Value;
        public string Active => strings["Location.Active"].Value;
        public string BrowserMessage => strings["Location.BrowserMessage"].Value;
        public string Coordinates => strings["Location.Coordinates"].Value;
        public string Correct => strings["Location.Correct"].Value;
        public string DefaultPosition => strings["Location.DefaultPosition"].Value;
        public string Denied => strings["Location.Denied"].Value;
        public string DismissWarning => strings["Location.DismissWarning"].Value;
        public string Error => strings["Location.Error"].Value;
        public string ErrorTitle => strings["Location.ErrorTitle"].Value;
        public string Get => strings["Location.Get"].Value;
        public string Getting => strings["Location.Getting"].Value;
        public string GpsPosition => strings["Location.GpsPosition"].Value;
        public string HttpsRequired => strings["Location.HttpsRequired"].Value;
        public string InsecureConnection => strings["Location.InsecureConnection"].Value;
        public string InsecureHost(object arg0) => strings["Location.InsecureHost", arg0].Value;
        public string LocalhostHint => strings["Location.LocalhostHint"].Value;
        public string ManualFallback => strings["Location.ManualFallback"].Value;
        public string Mark => strings["Location.Mark"].Value;
        public string MarkTitle => strings["Location.MarkTitle"].Value;
        public string NavigationHint => strings["Location.NavigationHint"].Value;
        public string NetworkAcquired => strings["Location.NetworkAcquired"].Value;
        public string NotSet => strings["Location.NotSet"].Value;
        public string OrMark => strings["Location.OrMark"].Value;
        public string PermissionHint => strings["Location.PermissionHint"].Value;
        public string ProvisionalCoordinates(object arg0, object arg1) => strings["Location.ProvisionalCoordinates", arg0, arg1].Value;
        public string ProvisionalHint => strings["Location.ProvisionalHint"].Value;
        public string Refresh => strings["Location.Refresh"].Value;
        public string SecureHint => strings["Location.SecureHint"].Value;
        public string SelectHint => strings["Location.SelectHint"].Value;
        public string SelectInZone => strings["Location.SelectInZone"].Value;
        public string SelectedCoordinates(object arg0, object arg1) => strings["Location.SelectedCoordinates", arg0, arg1].Value;
        public string SelectionMode => strings["Location.SelectionMode"].Value;
        public string Set => strings["Location.Set"].Value;
        public string Timeout => strings["Location.Timeout"].Value;
        public string Unavailable => strings["Location.Unavailable"].Value;
        public string Unsupported => strings["Location.Unsupported"].Value;
        public string Verify => strings["Location.Verify"].Value;
        public string YourPosition => strings["Location.YourPosition"].Value;
    }

    public sealed class MapText(IStringLocalizer<UiStrings> strings)
    {
        public string AssemblyPoint => strings["Map.AssemblyPoint"].Value;
        public string Blockade => strings["Map.Blockade"].Value;
        public string BlockadeName(object arg0) => strings["Map.BlockadeName", arg0].Value;
        public string BlockadePosition(object arg0, object arg1) => strings["Map.BlockadePosition", arg0, arg1].Value;
        public string Blockades => strings["Map.Blockades"].Value;
        public string Center => strings["Map.Center"].Value;
        public string CollapseInfo => strings["Map.CollapseInfo"].Value;
        public string Contributors => strings["Map.Contributors"].Value;
        public string EvacuationZone => strings["Map.EvacuationZone"].Value;
        public string EvacuationZoneName(object arg0) => strings["Map.EvacuationZoneName", arg0].Value;
        public string EvacuationZones => strings["Map.EvacuationZones"].Value;
        public string ExpandInfo => strings["Map.ExpandInfo"].Value;
        public string FeatureSummary(object arg0, object arg1) => strings["Map.FeatureSummary", arg0, arg1].Value;
        public string Features => strings["Map.Features"].Value;
        public string FitShelters => strings["Map.FitShelters"].Value;
        public string GestureHint => strings["Map.GestureHint"].Value;
        public string HideZone => strings["Map.HideZone"].Value;
        public string Length(object arg0) => strings["Map.Length", arg0].Value;
        public string NoZone => strings["Map.NoZone"].Value;
        public string Radius(object arg0) => strings["Map.Radius", arg0].Value;
        public string ResetView => strings["Map.ResetView"].Value;
        public string SafeLocation => strings["Map.SafeLocation"].Value;
        public string SafeLocations => strings["Map.SafeLocations"].Value;
        public string SafePoint => strings["Map.SafePoint"].Value;
        public string SafeZone => strings["Map.SafeZone"].Value;
        public string SafeZoneName(object arg0) => strings["Map.SafeZoneName", arg0].Value;
        public string Vertices(object arg0) => strings["Map.Vertices", arg0].Value;
        public string ZoneInfo => strings["Map.ZoneInfo"].Value;
        public string ZoomIn => strings["Map.ZoomIn"].Value;
        public string ZoomOut => strings["Map.ZoomOut"].Value;
    }

    public sealed class NavigationText(IStringLocalizer<UiStrings> strings)
    {
        public string Demo => strings["Navigation.Demo"].Value;
        public string DemoTitle => strings["Navigation.DemoTitle"].Value;
        public string Label => strings["Navigation.Label"].Value;
        public string Map => strings["Navigation.Map"].Value;
        public string MapTitle => strings["Navigation.MapTitle"].Value;
        public string Menu => strings["Navigation.Menu"].Value;
        public string NotFound => strings["Navigation.NotFound"].Value;
        public string NotFoundDescription => strings["Navigation.NotFoundDescription"].Value;
        public string Simulator => strings["Navigation.Simulator"].Value;
    }

    public sealed class PublishText(IStringLocalizer<UiStrings> strings)
    {
        public string Address => strings["Publish.Address"].Value;
        public string AssemblyPoints => strings["Publish.AssemblyPoints"].Value;
        public string Blockades => strings["Publish.Blockades"].Value;
        public string ChangeSettings => strings["Publish.ChangeSettings"].Value;
        public string CitizenView => strings["Publish.CitizenView"].Value;
        public string CloseProjector => strings["Publish.CloseProjector"].Value;
        public string CodeLabel => strings["Publish.CodeLabel"].Value;
        public string CopyFailed => strings["Publish.CopyFailed"].Value;
        public string CopyLink => strings["Publish.CopyLink"].Value;
        public string CopySuccess => strings["Publish.CopySuccess"].Value;
        public string Description => strings["Publish.Description"].Value;
        public string HttpError(object arg0) => strings["Publish.HttpError", arg0].Value;
        public string LinkCopied => strings["Publish.LinkCopied"].Value;
        public string LinkLabel => strings["Publish.LinkLabel"].Value;
        public string NextPerson => strings["Publish.NextPerson"].Value;
        public string OpenHint => strings["Publish.OpenHint"].Value;
        public string Plan => strings["Publish.Plan"].Value;
        public string Projector => strings["Publish.Projector"].Value;
        public string ProjectorHint => strings["Publish.ProjectorHint"].Value;
        public string ProjectorTitle => strings["Publish.ProjectorTitle"].Value;
        public string Publishing => strings["Publish.Publishing"].Value;
        public string PublishingPlan => strings["Publish.PublishingPlan"].Value;
        public string QrLabel => strings["Publish.QrLabel"].Value;
        public string Ready => strings["Publish.Ready"].Value;
        public string ReviewHint => strings["Publish.ReviewHint"].Value;
        public string Scan => strings["Publish.Scan"].Value;
        public string Scenario => strings["Publish.Scenario"].Value;
        public string SessionCode(object arg0) => strings["Publish.SessionCode", arg0].Value;
        public string SettingsDescription => strings["Publish.SettingsDescription"].Value;
        public string ShareHint => strings["Publish.ShareHint"].Value;
        public string ShareInstructions => strings["Publish.ShareInstructions"].Value;
        public string ShareTitle => strings["Publish.ShareTitle"].Value;
        public string Submit => strings["Publish.Submit"].Value;
        public string Success => strings["Publish.Success"].Value;
        public string Summary(object arg0, object arg1, object arg2) => strings["Publish.Summary", arg0, arg1, arg2].Value;
        public string Title => strings["Publish.Title"].Value;
        public string Zones => strings["Publish.Zones"].Value;
    }

    public sealed class ScenarioText(IStringLocalizer<UiStrings> strings)
    {
        public string Actions => strings["Scenario.Actions"].Value;
        public string Active => strings["Scenario.Active"].Value;
        public string Branch => strings["Scenario.Branch"].Value;
        public string BranchCurrent => strings["Scenario.BranchCurrent"].Value;
        public string BranchFrom => strings["Scenario.BranchFrom"].Value;
        public string BranchName => strings["Scenario.BranchName"].Value;
        public string ClearFilter => strings["Scenario.ClearFilter"].Value;
        public string CopyDescription => strings["Scenario.CopyDescription"].Value;
        public string CopyFeatures => strings["Scenario.CopyFeatures"].Value;
        public string CopyTree => strings["Scenario.CopyTree"].Value;
        public string Count(object arg0) => strings["Scenario.Count", arg0].Value;
        public string CreateAndSwitch => strings["Scenario.CreateAndSwitch"].Value;
        public string CreateDescription => strings["Scenario.CreateDescription"].Value;
        public string CreateTitle => strings["Scenario.CreateTitle"].Value;
        public string Creating => strings["Scenario.Creating"].Value;
        public string Current => strings["Scenario.Current"].Value;
        public string Delete => strings["Scenario.Delete"].Value;
        public string DeleteConfirm(object arg0) => strings["Scenario.DeleteConfirm", arg0].Value;
        public string DeleteNamed(object arg0) => strings["Scenario.DeleteNamed", arg0].Value;
        public string Description => strings["Scenario.Description"].Value;
        public string DescriptionHint => strings["Scenario.DescriptionHint"].Value;
        public string FeatureSummary(object arg0, object arg1, object arg2) => strings["Scenario.FeatureSummary", arg0, arg1, arg2].Value;
        public string Features => strings["Scenario.Features"].Value;
        public string Filter => strings["Scenario.Filter"].Value;
        public string FilterHint => strings["Scenario.FilterHint"].Value;
        public string Label => strings["Scenario.Label"].Value;
        public string Loading => strings["Scenario.Loading"].Value;
        public string NameExample => strings["Scenario.NameExample"].Value;
        public string NamePlaceholder => strings["Scenario.NamePlaceholder"].Value;
        public string NameRequired => strings["Scenario.NameRequired"].Value;
        public string NewBranch => strings["Scenario.NewBranch"].Value;
        public string NoMatches => strings["Scenario.NoMatches"].Value;
        public string OpenTree(object arg0) => strings["Scenario.OpenTree", arg0].Value;
        public string Parent => strings["Scenario.Parent"].Value;
        public string Root => strings["Scenario.Root"].Value;
        public string Session(object arg0) => strings["Scenario.Session", arg0].Value;
        public string Switch => strings["Scenario.Switch"].Value;
        public string SwitchHint => strings["Scenario.SwitchHint"].Value;
        public string Tree => strings["Scenario.Tree"].Value;
        public string TreeCopied => strings["Scenario.TreeCopied"].Value;
    }

    public sealed class ShelterText(IStringLocalizer<UiStrings> strings)
    {
        public string Allocation => strings["Shelter.Allocation"].Value;
        public string AllocationTitle => strings["Shelter.AllocationTitle"].Value;
        public string Criterion => strings["Shelter.Criterion"].Value;
        public string DecreaseDistance => strings["Shelter.DecreaseDistance"].Value;
        public string DecreaseOccupancy => strings["Shelter.DecreaseOccupancy"].Value;
        public string DefaultName => strings["Shelter.DefaultName"].Value;
        public string Distance => strings["Shelter.Distance"].Value;
        public string DistanceArrow => strings["Shelter.DistanceArrow"].Value;
        public string DistanceLabel => strings["Shelter.DistanceLabel"].Value;
        public string DistanceOnly => strings["Shelter.DistanceOnly"].Value;
        public string DistancePercent(object arg0) => strings["Shelter.DistancePercent", arg0].Value;
        public string DistanceValue(object arg0) => strings["Shelter.DistanceValue", arg0].Value;
        public string DistanceWeight => strings["Shelter.DistanceWeight"].Value;
        public string Full => strings["Shelter.Full"].Value;
        public string IncreaseDistance => strings["Shelter.IncreaseDistance"].Value;
        public string IncreaseOccupancy => strings["Shelter.IncreaseOccupancy"].Value;
        public string Label => strings["Shelter.Label"].Value;
        public string Occupancy => strings["Shelter.Occupancy"].Value;
        public string OccupancyArrow => strings["Shelter.OccupancyArrow"].Value;
        public string OccupancyLabel => strings["Shelter.OccupancyLabel"].Value;
        public string OccupancyLabelAccessible => strings["Shelter.OccupancyLabelAccessible"].Value;
        public string OccupancyOnly => strings["Shelter.OccupancyOnly"].Value;
        public string OccupancyPercent(object arg0) => strings["Shelter.OccupancyPercent", arg0].Value;
        public string OccupancySummary(object arg0, object arg1, object arg2) => strings["Shelter.OccupancySummary", arg0, arg1, arg2].Value;
        public string OccupancyValue(object arg0) => strings["Shelter.OccupancyValue", arg0].Value;
        public string OccupancyWeight => strings["Shelter.OccupancyWeight"].Value;
        public string PeopleCount(object arg0) => strings["Shelter.PeopleCount", arg0].Value;
        public string PeopleHere => strings["Shelter.PeopleHere"].Value;
        public string Places(object arg0, object arg1) => strings["Shelter.Places", arg0, arg1].Value;
        public string PresetA => strings["Shelter.PresetA"].Value;
        public string PresetB => strings["Shelter.PresetB"].Value;
        public string PresetC => strings["Shelter.PresetC"].Value;
        public string Presets => strings["Shelter.Presets"].Value;
        public string ResetOccupancy => strings["Shelter.ResetOccupancy"].Value;
        public string SelectHint => strings["Shelter.SelectHint"].Value;
        public string WeightsLabel => strings["Shelter.WeightsLabel"].Value;
        public string WeightsValue(object arg0, object arg1) => strings["Shelter.WeightsValue", arg0, arg1].Value;
    }

    public sealed class SimulationText(IStringLocalizer<UiStrings> strings)
    {
        public string ActualSpeed(object arg0, object arg1) => strings["Simulation.ActualSpeed", arg0, arg1].Value;
        public string AgentCount => strings["Simulation.AgentCount"].Value;
        public string AgentCountLabel => strings["Simulation.AgentCountLabel"].Value;
        public string AgentCountValue(object arg0) => strings["Simulation.AgentCountValue", arg0].Value;
        public string AgentPerDotUnit => strings["Simulation.AgentPerDotUnit"].Value;
        public string AgentPositions => strings["Simulation.AgentPositions"].Value;
        public string AgentSpeed => strings["Simulation.AgentSpeed"].Value;
        public string AgentSummary(object arg0, object arg1) => strings["Simulation.AgentSummary", arg0, arg1].Value;
        public string AgentViewHint => strings["Simulation.AgentViewHint"].Value;
        public string Agents => strings["Simulation.Agents"].Value;
        public string AgentsPerDot => strings["Simulation.AgentsPerDot"].Value;
        public string AgentsPerDotLabel => strings["Simulation.AgentsPerDotLabel"].Value;
        public string AgentsPerDotUnit => strings["Simulation.AgentsPerDotUnit"].Value;
        public string AgentsPerDotValue(object arg0) => strings["Simulation.AgentsPerDotValue", arg0].Value;
        public string ChangeSpeed => strings["Simulation.ChangeSpeed"].Value;
        public string Close => strings["Simulation.Close"].Value;
        public string CloseHint => strings["Simulation.CloseHint"].Value;
        public string Completed => strings["Simulation.Completed"].Value;
        public string Controls => strings["Simulation.Controls"].Value;
        public string Coordinates(object arg0, object arg1) => strings["Simulation.Coordinates", arg0, arg1].Value;
        public string Current => strings["Simulation.Current"].Value;
        public string Defaults => strings["Simulation.Defaults"].Value;
        public string Density => strings["Simulation.Density"].Value;
        public string DensityMap => strings["Simulation.DensityMap"].Value;
        public string DestinationRequired => strings["Simulation.DestinationRequired"].Value;
        public string Diagnostics => strings["Simulation.Diagnostics"].Value;
        public string Dimensions => strings["Simulation.Dimensions"].Value;
        public string DimensionsValue(object arg0, object arg1) => strings["Simulation.DimensionsValue", arg0, arg1].Value;
        public string DismissMessage => strings["Simulation.DismissMessage"].Value;
        public string DisplayMode => strings["Simulation.DisplayMode"].Value;
        public string DisplayRefresh => strings["Simulation.DisplayRefresh"].Value;
        public string DisplayRefreshOption => strings["Simulation.DisplayRefreshOption"].Value;
        public string DisplaySettings => strings["Simulation.DisplaySettings"].Value;
        public string DotCount(object arg0) => strings["Simulation.DotCount", arg0].Value;
        public string Elapsed => strings["Simulation.Elapsed"].Value;
        public string Ended => strings["Simulation.Ended"].Value;
        public string Engine => strings["Simulation.Engine"].Value;
        public string EngineHint => strings["Simulation.EngineHint"].Value;
        public string Evacuated => strings["Simulation.Evacuated"].Value;
        public string EvacuatedProgress(object arg0, object arg1) => strings["Simulation.EvacuatedProgress", arg0, arg1].Value;
        public string Evacuation => strings["Simulation.Evacuation"].Value;
        public string FlowParticles => strings["Simulation.FlowParticles"].Value;
        public string FpsLimit => strings["Simulation.FpsLimit"].Value;
        public string Live => strings["Simulation.Live"].Value;
        public string LoadingParameters => strings["Simulation.LoadingParameters"].Value;
        public string MapDisplay => strings["Simulation.MapDisplay"].Value;
        public string MaxAgentsPerDot => strings["Simulation.MaxAgentsPerDot"].Value;
        public string OneAgentPerDot => strings["Simulation.OneAgentPerDot"].Value;
        public string OpenSettings => strings["Simulation.OpenSettings"].Value;
        public string Parameters => strings["Simulation.Parameters"].Value;
        public string Pause => strings["Simulation.Pause"].Value;
        public string PauseHint => strings["Simulation.PauseHint"].Value;
        public string Paused => strings["Simulation.Paused"].Value;
        public string PhysicsDescription => strings["Simulation.PhysicsDescription"].Value;
        public string PopulationSettings => strings["Simulation.PopulationSettings"].Value;
        public string Preparing => strings["Simulation.Preparing"].Value;
        public string RayLength => strings["Simulation.RayLength"].Value;
        public string RayLengthLabel => strings["Simulation.RayLengthLabel"].Value;
        public string RealTime => strings["Simulation.RealTime"].Value;
        public string RenderFps(object arg0) => strings["Simulation.RenderFps", arg0].Value;
        public string Repulsion => strings["Simulation.Repulsion"].Value;
        public string RepulsionLabel => strings["Simulation.RepulsionLabel"].Value;
        public string RepulsionValue(object arg0) => strings["Simulation.RepulsionValue", arg0].Value;
        public string Reset => strings["Simulation.Reset"].Value;
        public string ResetAgents => strings["Simulation.ResetAgents"].Value;
        public string ResetHint => strings["Simulation.ResetHint"].Value;
        public string ResumeHint => strings["Simulation.ResumeHint"].Value;
        public string Run => strings["Simulation.Run"].Value;
        public string Running => strings["Simulation.Running"].Value;
        public string SensorHint => strings["Simulation.SensorHint"].Value;
        public string Sensors => strings["Simulation.Sensors"].Value;
        public string Settings => strings["Simulation.Settings"].Value;
        public string SettingsDescription => strings["Simulation.SettingsDescription"].Value;
        public string SettingsTitle => strings["Simulation.SettingsTitle"].Value;
        public string ShowSensors => strings["Simulation.ShowSensors"].Value;
        public string Speed => strings["Simulation.Speed"].Value;
        public string SpeedLabel => strings["Simulation.SpeedLabel"].Value;
        public string SpeedMap => strings["Simulation.SpeedMap"].Value;
        public string SpeedSettings => strings["Simulation.SpeedSettings"].Value;
        public string Start => strings["Simulation.Start"].Value;
        public string StartAction => strings["Simulation.StartAction"].Value;
        public string StartFailed(object arg0) => strings["Simulation.StartFailed", arg0].Value;
        public string Status => strings["Simulation.Status"].Value;
        public string StatusLabel => strings["Simulation.StatusLabel"].Value;
        public string Step => strings["Simulation.Step"].Value;
        public string StepHint => strings["Simulation.StepHint"].Value;
        public string StepsPerSecond(object arg0) => strings["Simulation.StepsPerSecond", arg0].Value;
        public string Stop => strings["Simulation.Stop"].Value;
        public string StopAction => strings["Simulation.StopAction"].Value;
        public string Stopped => strings["Simulation.Stopped"].Value;
        public string StreetPositions => strings["Simulation.StreetPositions"].Value;
        public string TargetSpeed(object arg0) => strings["Simulation.TargetSpeed", arg0].Value;
        public string Units(object arg0) => strings["Simulation.Units", arg0].Value;
        public string Unlimited => strings["Simulation.Unlimited"].Value;
        public string UnlimitedOption => strings["Simulation.UnlimitedOption"].Value;
        public string WebGpuUnavailable => strings["Simulation.WebGpuUnavailable"].Value;
        public string ZoneRequired => strings["Simulation.ZoneRequired"].Value;
    }

    public sealed class StatisticsText(IStringLocalizer<UiStrings> strings)
    {
        public string AllCharts => strings["Statistics.AllCharts"].Value;
        public string AverageDensity => strings["Statistics.AverageDensity"].Value;
        public string AverageSpeed => strings["Statistics.AverageSpeed"].Value;
        public string Bottleneck => strings["Statistics.Bottleneck"].Value;
        public string ChartKey => strings["Statistics.ChartKey"].Value;
        public string CohortDescription => strings["Statistics.CohortDescription"].Value;
        public string CohortDuration => strings["Statistics.CohortDuration"].Value;
        public string CohortTitle => strings["Statistics.CohortTitle"].Value;
        public string Cohorts => strings["Statistics.Cohorts"].Value;
        public string CompletedCohorts(object arg0, object arg1) => strings["Statistics.CompletedCohorts", arg0, arg1].Value;
        public string Critical => strings["Statistics.Critical"].Value;
        public string DensityAxis => strings["Statistics.DensityAxis"].Value;
        public string DensityBand => strings["Statistics.DensityBand"].Value;
        public string DensityDescription => strings["Statistics.DensityDescription"].Value;
        public string DensityLegend => strings["Statistics.DensityLegend"].Value;
        public string DensitySummary => strings["Statistics.DensitySummary"].Value;
        public string DensityTitle => strings["Statistics.DensityTitle"].Value;
        public string DensityUnit => strings["Statistics.DensityUnit"].Value;
        public string Evacuated => strings["Statistics.Evacuated"].Value;
        public string EvacuatedLabel => strings["Statistics.EvacuatedLabel"].Value;
        public string Freeflow => strings["Statistics.Freeflow"].Value;
        public string Jam => strings["Statistics.Jam"].Value;
        public string Label => strings["Statistics.Label"].Value;
        public string MeanSpeed => strings["Statistics.MeanSpeed"].Value;
        public string MeanSpeedLabel => strings["Statistics.MeanSpeedLabel"].Value;
        public string NoData => strings["Statistics.NoData"].Value;
        public string OpenHint => strings["Statistics.OpenHint"].Value;
        public string PeakDensityLabel => strings["Statistics.PeakDensityLabel"].Value;
        public string PopulationCohort => strings["Statistics.PopulationCohort"].Value;
        public string Queue => strings["Statistics.Queue"].Value;
        public string ReferenceThresholds => strings["Statistics.ReferenceThresholds"].Value;
        public string ResetPosition => strings["Statistics.ResetPosition"].Value;
        public string SimulationTime => strings["Statistics.SimulationTime"].Value;
        public string SpeedAxis => strings["Statistics.SpeedAxis"].Value;
        public string SpeedDescription => strings["Statistics.SpeedDescription"].Value;
        public string SpeedLegend => strings["Statistics.SpeedLegend"].Value;
        public string SpeedProfile => strings["Statistics.SpeedProfile"].Value;
        public string SpeedTitle => strings["Statistics.SpeedTitle"].Value;
        public string StandardDeviation => strings["Statistics.StandardDeviation"].Value;
        public string StartHint => strings["Statistics.StartHint"].Value;
        public string TimeAxis => strings["Statistics.TimeAxis"].Value;
        public string TimeLabel => strings["Statistics.TimeLabel"].Value;
        public string Title => strings["Statistics.Title"].Value;
    }

    public sealed class TourText(IStringLocalizer<UiStrings> strings)
    {
        public string Back => strings["Tour.Back"].Value;
        public string BlockadeBody => strings["Tour.BlockadeBody"].Value;
        public string BlockadeTitle => strings["Tour.BlockadeTitle"].Value;
        public string CircleBody => strings["Tour.CircleBody"].Value;
        public string CircleTitle => strings["Tour.CircleTitle"].Value;
        public string Close => strings["Tour.Close"].Value;
        public string ControlsBody => strings["Tour.ControlsBody"].Value;
        public string ControlsTitle => strings["Tour.ControlsTitle"].Value;
        public string Done => strings["Tour.Done"].Value;
        public string EvacuationBody => strings["Tour.EvacuationBody"].Value;
        public string EvacuationTitle => strings["Tour.EvacuationTitle"].Value;
        public string Next => strings["Tour.Next"].Value;
        public string PolygonBody => strings["Tour.PolygonBody"].Value;
        public string PolygonTitle => strings["Tour.PolygonTitle"].Value;
        public string Progress => strings["Tour.Progress"].Value;
        public string RemoveBody => strings["Tour.RemoveBody"].Value;
        public string RemoveTitle => strings["Tour.RemoveTitle"].Value;
        public string Replay => strings["Tour.Replay"].Value;
        public string SafeBody => strings["Tour.SafeBody"].Value;
        public string SafeTitle => strings["Tour.SafeTitle"].Value;
        public string SettingsBody => strings["Tour.SettingsBody"].Value;
        public string SettingsTitle => strings["Tour.SettingsTitle"].Value;
        public string SimulationBody => strings["Tour.SimulationBody"].Value;
        public string SimulationTitle => strings["Tour.SimulationTitle"].Value;
        public string WelcomeBody => strings["Tour.WelcomeBody"].Value;
        public string WelcomeTitle => strings["Tour.WelcomeTitle"].Value;
        public string ZoneBody => strings["Tour.ZoneBody"].Value;
        public string ZoneTitle => strings["Tour.ZoneTitle"].Value;
    }
}
